### ISSUE TITLE
metrics empty

### ISSUE THREAD

**Issue by bboysoulcn** [atuinsh/atuin#1450]
env 

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atuin
  namespace: app
spec:
  selector:
    matchLabels:
      app: atuin
  serviceName: atuin
  replicas: 1
  template:
    metadata:
      labels:
        app: atuin
    spec:
      containers:
        - name: atuin
          image: ghcr.io/atuinsh/atuin:17.1.0
          args:
            - "server"
            - "start"
          env:
            - name: ATUIN_HOST
              value: "0.0.0.0"
            - name: ATUIN_PORT
              value: "8888"
            - name: ATUIN_OPEN_REGISTRATION
              value: 'true'
            - name: ATUIN_DB_URI
              value: postgres://atuin:xxx@postgresql.xxx.cn:5433/atuin
            - name: ATUIN_METRICS__HOST
              value: "0.0.0.0"
            - name: ATUIN_METRICS__ENABLE
              value: "true"
            - name: ATUIN_METRICS__PORT
              value: "9001"
          volumeMounts:
            - name: atuin-data
              mountPath: /config
          ports:
            - containerPort: 8888
              name: web
            - containerPort: 9001
              name: metrics
  volumeClaimTemplates:
    - metadata:
        name: atuin-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: managed-nfs-storage
        resources:
          requests:
            storage: 200Gi
```

```bash
❯ curl -I http://localhost:9001/metrics
HTTP/1.1 200 OK
content-type: text/plain; charset=utf-8
content-length: 5794
date: Fri, 15 Dec 2023 06:05:53 GMT
```
