### ISSUE TITLE
Make directory filtering relative to $HOME

### ISSUE THREAD

**Issue by ellie** [atuinsh/atuin#1679]
Discussion: https://forum.atuin.sh/t/make-directory-filtering-relative-to-user-home/128

This means that when filtering by directory

- /home/ellie/foo

and

- /Users/ellie/foo

Will show as the "same" on two different systems.

**Comment by offbyone** [comment]
Interesting question; I could also see a use for this, but I'm not sure what the implications would be.  I see two paths:

1. Atuin has some feature for mapping a known set of path prefixes as "common"; when searching for `cwd` we search for all common prefixes.
2. Atuin's store is modified to replace the user's home directory with a marker (`~`) when writing the path

In the case of (2) it's not clear what needs to happen with older entries, or if they need to be updated in the DB or just on local sync.

**Comment by j-xella** [comment]
I would actually propose to extend this further. Here is my use case: I work on a project that is cross-platform, so I have a git clone on both windows and linux machines. The workspaces are in totally different locations compared to home folder, but within the working copies, the structure is the same. I would like to be able to see all the commands I run inside this project, on all machines.

I imagine creating something like folder groups:

```toml
[Project_A]
machine_A = /path/to/project_A
machine_B = C:\path\to\project_A

[Project_B]
machine_A = /path/to/project_B
machine_B = C:\path\to\project_B

[HOME]
machine_A = /home/userX
machine_B = C:\users\userX
```

Then, if I am on `machine_A` in a folder that is a subfolder of `/path/to/project_A`, then the "same folder" commands should also include commands from `machine_B` from the same subfolder of `C:\path\to\project_A`
