### ISSUE TITLE
crashed on zsh 

### ISSUE THREAD

**Issue by mohammedbilalns** [atuinsh/atuin#1870]
atuin crashed on zsh shows 

```
Error: pool timed out while waiting for an open connection

Location:
    atuin/src/command/client.rs:102:18
```

**Comment by mohammedbilalns** [comment]
```
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.1.0
  sync: null
shell:
  name: zsh
  plugins: []
system:
  os: Arch Linux
  arch: x86_64
  version: unknown
  disks:
  - name: /dev/nvme0n1p5
    filesystem: ext4
  - name: /dev/nvme0n1p4
    filesystem: vfat
  - name: /dev/sda3
    filesystem: ext4
  - name: /dev/sda5
    filesystem: fuseblk
```
