### ISSUE TITLE
[Bug]: Inspector draws bar chart bar over corresponding number of exit codes

### ISSUE THREAD

**Issue by ednolan** [atuinsh/atuin#1881]
### What did you expect to happen?

I expected to be able to see the number of times that my command exited with exit code 2

### What happened?

The inspector drew the histogram bar over the data:
```
┌Exit code distribution
│    ███
│    ███ ▇▇▇
│ 7  759 491 ▇▇▇  2
│-1   0   1   2  130
└──────────────────────
```

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics

[Filesystem] ZFS is known to have some issues with SQLite. Atuin uses SQLite heavily. If you are having poor performance, there are some workarounds here: https://github.com/atuinsh/atuin/issues/952

Please include the output below with any bug reports or issues

atuin:
  version: 18.1.0
  sync:
    cloud: false
    records: true
    auto_sync: true
    last_sync: 2024-03-14 16:06:43.500113827 +00:00:00
shell:
  name: bash
  plugins:
  - atuin
  - bash-preexec
system:
  os: Ubuntu
  arch: x86_64
  version: '23.10'
  disks:
    (redacted)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
