### ISSUE TITLE
[Bug]: `atuin import auto` doesn't work for xonsh?

### ISSUE THREAD

**Issue by tkossak** [atuinsh/atuin#1884]
### What did you expect to happen?

When I run
`atuin import auto`
or
`atuin import xonsh`

I expect atuin to import my xonsh history

### What happened?

Instead I get error:

```
        Atuin
======================
          🌍
       🐘🐘🐘🐘
          🐢
======================
Importing history...
Importing history from xonsh
Error: Could not find history file "/home/kossak/.local/share/xonsh/history_json". Try setting $HISTFILE

Location:
    /home/kossak/.cargo/registry/src/index.crates.io-6f17d22bba15001f/atuin-client-18.1.0/src/import/mod.rs:91:9
```

I have xonsh v0.15.1 and the folder with all history files is present:
```
$ ls -ld /home/kossak/.local/share/xonsh/history_json
drwxr-xr-x 2 kossak kossak 147456 03-15 10:24 /home/kossak/.local/share/xonsh/history_json
```

### Atuin doctor output

```yaml
atuin:
  version: 18.1.0
  sync: null
shell:
  name: xonsh
  plugins: []
system:
  os: Manjaro Linux
  arch: x86_64
  version: 23.1.3
  disks:
  - name: /dev/sdb4
    filesystem: ext4
  - name: /dev/sdb5
    filesystem: ext4
  - name: /dev/sda2
    filesystem: ext4
  - name: /dev/sdb6
    filesystem: fuseblk
  - name: /dev/sdb3
    filesystem: fuseblk
  - name: /dev/sdb1
    filesystem: vfat
  - name: /dev/sda1
    filesystem: fuseblk
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blarghmatey** [comment]
I'm running into this same error.
```
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.1.0
  sync:
    cloud: true
    records: false
    auto_sync: true
    last_sync: 2024-03-30 13:31:15.267749251 +00:00:00
shell:
  name: xonsh
  plugins: []
system:
  os: Manjaro Linux
  arch: x86_64
  version: 23.1.3
  disks:
  - name: none
    filesystem: 9p
  - name: none
    filesystem: overlay
  - name: /dev/sdc
    filesystem: ext4
  - name: /dev/sdc
    filesystem: ext4
  - name: none
    filesystem: overlay
  - name: none
    filesystem: overlay
  - name: none
    filesystem: overlay
  - name: C:\134
    filesystem: 9p
  - name: /dev/sdc
    filesystem: ext4
```
