### ISSUE TITLE
[Bug]: attempting to decrypt with incorrect key

### ISSUE THREAD

**Issue by abs3ntdev** [atuinsh/atuin#1895]
### What did you expect to happen?

atuin sync completes with no errors

### What happened?

i get an error saying:

```
0/0 up/down to record store
53667 in history index, but 37153 in history store
Running automatic history store init...
Error: attempting to decrypt with incorrect key. currently using ***, expecting ***

Location:
    atuin-client/src/record/encryption.rs:132:9
```

### Atuin doctor output

```yaml
atuin:
  version: 18.1.0
  sync:
    cloud: false
    records: true
    auto_sync: true
    last_sync: 2024-03-21 6:58:58.225402477 +00:00:00
shell:
  name: zsh
  plugins:
  - atuin
system:
  os: Arch Linux
  arch: x86_64
  version: unknown
  disks:
  - name: /dev/nvme0n1p3
    filesystem: ext4
  - name: /dev/nvme0n1p1
    filesystem: vfat
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
