### ISSUE TITLE
[Bug]: Interaction between workspaces and filter_mode_shell_up_key_binding

### ISSUE THREAD

**Issue by Zach-Johnson** [atuinsh/atuin#1896]
### What did you expect to happen?

I set my config to this:
```
workspaces = true
filter_mode_shell_up_key_binding = "session"
```
and I expect that up arrow will default to session view

### What happened?

It filters to the workspace view. I would like it to still filter up arrow to the session view, as this is very useful for running the previous command that was ran in a particular session easily. Otherwise I have to search for the previous command. This is very useful for example, when running some process locally and wanting to restart it.

### Atuin doctor output

```yaml
atuin:
  version: 18.1.0
  sync: null
shell:
  name: bash
  plugins:
  - atuin
system:
  os: Darwin
  arch: arm64
  version: 13.6.5
  disks:
  - name: Macintosh HD
    filesystem: apfs
  - name: Macintosh HD
    filesystem: apfs
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
