### ISSUE TITLE
[Bug]: "stripe listen --api-key ..." command is not saved into the history

### ISSUE THREAD

**Issue by delgermurun** [atuinsh/atuin#1903]
### What did you expect to happen?

`stripe listen --api-key sk_test_... --forward-to localhost:3000/webhook/stripe`

After running first time, I want to re-run from the history.

### What happened?

This command doesn't get saved in the history; I've run it multiple times but can't find it. Is this expected behavior?

### Atuin doctor output

```yaml
$ atuin doctor
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.1.0
  sync: null
shell:
  name: zsh
  plugins:
  - atuin
system:
  os: Darwin
  arch: arm64
  version: '14.4'
  disks:
  - name: Macintosh HD
    filesystem: apfs
  - name: Macintosh HD
    filesystem: apfs
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
