### ISSUE TITLE
[Bug]: Repeated commands with different arguments, flags, options are not in history

### ISSUE THREAD

**Issue by Teufen** [atuinsh/atuin#1907]
### What did you expect to happen?

When using the same command but with different arguments, flags and/or options I would like to see them all in my history.

### What happened?

Only the first occurrence of the command showed up in my history.

```
10:59 $ python2 manage.py dumpdata --help
11:03 $ python2 manage.py dumpdata -o assetmgmt/fixtures/categories_states_types assetmgmt.AssetCategory assetmgmt.AssetState assetmgmt.InterventionState assetmgmt.InterventionType
11:37 $ python2 manage.py dumpdata --format=json --indent=3 -o assetmgmt/fixtures/categories_states_types.json -v1 assetmgmt.AssetCategory assetmgmt.AssetState assetmgmt.InterventionState assetmgmt.InterventionType
```

And then after hitting `ctrl-r`

![image](https://github.com/atuinsh/atuin/assets/7165090/80ff2bf6-8d7c-4d6c-8d73-966f79753c23)

### Atuin doctor output

```yaml
11:38 $ atuin doctor
error: unrecognized subcommand 'doctor'

Usage: atuin <COMMAND>

For more information, try '--help'.
✘-2 intranet [assetmgmt {origin/assetmgmt}|✚ 3…2]
11:52 $ atuin --version
atuin 18.0.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ellie** [comment]
Could you please update to the latest version and confirm if this is still an issue? v18.1

**Comment by Teufen** [comment]
I updated to the latest version, and the problem persists.

```
11:59 $ atuin doctor
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.1.0
  sync: null
shell:
  name: bash
  plugins:
  - atuin
  - bash-preexec
system:
  os: Debian GNU/Linux
  arch: x86_64
  version: '11'
  disks:
  - name: rootfs
    filesystem: lxfs
  - name: C:\134
    filesystem: drvfs 
```
