### ISSUE TITLE
[Bug]: Stats don't respect `ignored_commands`

### ISSUE THREAD

**Issue by bradleyfrank** [atuinsh/atuin#1919]
### What did you expect to happen?

My understanding is that the `ignored_commands` variable in the config are a list of commands that `atuin stats` should ignore when compiling command stats. My config is:

```cat
[develop:U]% cat ~/.config/atuin/config.toml
workspaces = true
show_preview = true
enter_accept = true
keymap_mode = "vim-insert"
ignored_commands = ["cd", "ls", "ll", "vim"]
```

I would have expected these commands to be excluded from stats.

### What happened?

Stats still include the commands I've excluded:

```sh
[develop:U]% atuin stats
[▮▮▮▮▮▮▮▮▮▮] 605 ll
[▮▮▮▮▮▮▮▮  ] 540 vim
[▮▮▮▮      ] 279 cd
[▮▮▮       ] 241 nb
[▮▮▮       ] 223 jq
[▮▮▮       ] 215 brew
[▮▮▮       ] 205 ansible-playbook
[▮▮▮       ] 193 rg
[▮▮        ] 137 git add
```

I have tried the following:

```sh
[develop:U]% atuin history init-store
  Import complete
[develop:U]% atuin history prune
No entries to prune.
```

### Atuin doctor output

```yaml
atuin:
  version: 18.1.0
  sync: null
shell:
  name: zsh
  plugins:
  - atuin
system:
  os: Darwin
  arch: arm64
  version: 14.4.1
  disks:
  - name: Macintosh HD
    filesystem: apfs
  - name: Macintosh HD
    filesystem: apfs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
