### ISSUE TITLE
[Bug]: Atuin doesn't store new commands for user 'root'

### ISSUE THREAD

**Issue by ibahnasy** [atuinsh/atuin#1921]
### What did you expect to happen?

Atuin stores new executed commands fine for any normal user and this should happen to the `root` user too.

### What happened?

This doesn't happen unless manually ran: `atuin import bash`.

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics

[Shell] If you are using Bash, Atuin requires that either bash-preexec or ble.sh be installed. We cannot currently detect ble, so if you have it setup then ignore this! Read more here: https://docs.atuin.sh/guide/installation/#bash

Please include the output below with any bug reports or issues

atuin:
  version: 18.1.0
  sync: null
shell:
  name: bash
  plugins:
  - atuin
system:
  os: Ubuntu
  arch: x86_64
  version: '23.10'
  disks:
  - name: /dev/mapper/ubuntu--vg-ubuntu--lv
    filesystem: ext4
  - name: /dev/nvme0n1p2
    filesystem: ext4
  - name: /dev/mapper/ubuntu--vg-ubuntu--lv
    filesystem: ext4
  - name: /dev/nvme0n1p1
    filesystem: vfat
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
