### ISSUE TITLE
[Nushell] [Bug]: Atuin breaks after a recent nushell update.

### ISSUE THREAD

**Issue by JustMarkov** [atuinsh/atuin#1922]
### What did you expect to happen?

After a recent nushell update, atuin breaks and doesn't work using the up arrow key. I expect to use the up arrow key as normal.

### What happened?

When pressing the up arrow key, nu gives an error that the "--redirect-stderr" flag is not supported.

```
Error: Deprecated flag
    Diagnostic severity: error
Begin snippet for entry #1 starting at line 1, column 1

snippet line 1: # b6a3c7be-bb82-44af-9800-2374376c6749
snippet line 2: commandline edit (ATUIN_LOG=error run-external --redirect-stderr atuin search "--shell-up-key-binding" "--interactive" "--" (commandline) | complete | $in.stderr | str substring ..-1)
    label at line 2, columns 48 to 137: `--redirect-stderr` is deprecated
diagnostic help: use the `e>|` stderr pipe redirection instead
```

### Atuin doctor output

```yaml
atuin:
  version: 18.1.0
  sync: null
shell:
  name: nu
  plugins: []
system:
  os: openSUSE Tumbleweed
  arch: x86_64
  version: '20240329'
  disks:
  - name: /dev/mapper/system-root
    filesystem: btrfs
  - name: /dev/nvme0n1p1
    filesystem: btrfs
  - name: /dev/mapper/system-home
    filesystem: btrfs
  - name: /dev/nvme1n1p1
    filesystem: vfat
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
