### ISSUE TITLE
[Bug]: Max Length for a command to be saved in Atuin

### ISSUE THREAD

**Issue by DakshChhokra** [atuinsh/atuin#1923]
### What did you expect to happen?

I have a terminal command(a go build and run command with many config flags) with over a 1,000 characters. It is no longer saved in atuin when I run it in my terminal. 

### What happened?

To run this command via atuin history, I have to go up until a few months back when it was last saved. 

When I create a random echo with 1000+ characters it works without any issues

### Atuin doctor output

```yaml
atuin:
  version: 18.1.0
  sync:
    cloud: true
    records: false
    auto_sync: true
    last_sync: 2024-04-04 16:46:28.018239 +00:00:00
shell:
  name: zsh
  plugins:
  - atuin
system:
  os: Darwin
  arch: x86_64
  version: 12.5.1
  disks:
  - name: Macintosh HD
    filesystem: apfs
  - name: Macintosh HD
    filesystem: apfs
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
