### ISSUE TITLE
Nushell integration broken with `Error:   × Deprecated flag`

### ISSUE THREAD

**Issue by avastmick** [atuinsh/atuin#1925]
### What did you expect to happen?

On `Up-arrow` or `CTRL-r` should give Altuin table of history.

![image](https://github.com/atuinsh/atuin/assets/16931995/68a454d2-8beb-4066-beff-d4f846c8c8a2)

### What happened?

Using:
```bash 
nu --version
0.92.1
```
On `Up-arrow` or `CRTL-r` the following is shown.

```bash
Error:   × Deprecated flag
   ╭─[entry #1:2:48]
 1 │ # 0678a285-31ee-4315-9e75-4f2436aef0a8
 2 │ commandline edit (ATUIN_LOG=error run-external --redirect-stderr atuin search "--shell-up-key-binding" "--interactive" "--" (commandline) | complete | $in.stderr | str substring ..-1)
   ·                                                ─────────────────────────────────────────────┬────────────────────────────────────────────
   ·                                                                                             ╰── `--redirect-stderr` is deprecated
   ╰────
  help: use the `e>|` stderr pipe redirection instead
```

Comes from `~/.local/share/atuin/init.nu` line 39:

```bash
def _atuin_search_cmd [...flags: string] {
    let nu_version = ($env.NU_VERSION | split row '.' | each { || into int })
    [
        $ATUIN_KEYBINDING_TOKEN,
        ([
            (if $nu_version.0 <= 0 and $nu_version.1 <= 90 { 'commandline' } else { 'commandline edit' }),
>this line            `(ATUIN_LOG=error run-external --redirect-stderr atuin search`,
            ($flags | append [--interactive, --] | each {|e| $'"($e)"'}),
            `(commandline) | complete | $in.stderr | str substring ..-1)`,
        ] | flatten | str join ' '),
    ] | str join "\n"
}

```

I've had a crack at modifying according the error message, but I get an unresponsive terminal. Sorry, I'm under the pump workwise... So I've had to turn Atuin off for now.

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.1.0
  sync: null
shell:
  name: nu
  plugins: []
system:
  os: Darwin
  arch: arm64
  version: 14.4.1
  disks:
  - name: Macintosh HD
    filesystem: apfs
  - name: Macintosh HD
    filesystem: apfs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
