### ISSUE TITLE
[Bug]: Can not introduce symbols

### ISSUE THREAD

**Issue by stkw0** [atuinsh/atuin#1926]
### What did you expect to happen?

Be able to search for symbols like "@" 

### What happened?

It prints the number disregarding the "Alt" key modifier

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.1.0
  sync: null
shell:
  name: zsh
  plugins:
  - atuin
system:
  os: Gentoo
  arch: x86_64
  version: '2.15'
  disks:
  - name: /dev/sda1
    filesystem: btrfs
  - name: /dev/sdc1
    filesystem: btrfs
  - name: /dev/nvme0n1p1
    filesystem: btrfs
  - name: /dev/sdc3
    filesystem: btrfs
  - name: /dev/sdc3
    filesystem: btrfs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
