### ISSUE TITLE
[Bug]: Keybind legend shows `<enter>: run` despite `enter_accept = false` in config

### ISSUE THREAD

**Issue by FredeEB** [atuinsh/atuin#1969]
### What did you expect to happen?

`<esc>: exit, <tab>: edit, <enter>: edit, <ctrl-o>: inspect`

I'm actually not sure if I like this, however, there's clearly a disconnect between the option and the action that will be applied on `<enter>`

### What happened?

`<esc>: exit, <tab>: edit, <enter>: run, <ctrl-o>: inspect`

### Atuin doctor output

```yaml
I atuin doctor
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.1.0
  sync: null
shell:
  name: bash
  plugins:
  - bash-preexec
  - atuin
system:
  os: NixOS
  arch: x86_64
  version: '24.05'
  disks:
  - name: /dev/disk/by-label/nixos
    filesystem: ext4
  - name: /dev/disk/by-label/nixos
    filesystem: ext4
  - name: /dev/nvme0n1p1
    filesystem: vfat
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
