### ISSUE TITLE
[Bug]: Up arrow when searching history exists Atuin and shows the [A character 

### ISSUE THREAD

**Issue by johndevor** [atuinsh/atuin#1981]
### What did you expect to happen?

I expected to be able to scroll up the history list with the up arrow.

### What happened?

Atuin closes and dumps me in the prompt with the [A character. 

e.g.

john@Johns-MBP-2 sdk % [A

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.2.0
  sync:
    cloud: true
    records: false
    auto_sync: true
    last_sync: 2024-04-27 6:06:45.191786 +00:00:00
shell:
  name: zsh
  default: zsh
  plugins:
  - atuin
system:
  os: Darwin
  arch: arm64
  version: '13.1'
  disks:
  - name: Macintosh HD
    filesystem: apfs
  - name: Macintosh HD
    filesystem: apfs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
