### ISSUE TITLE
[Bug]: Sync on self-hosted server returns 413

### ISSUE THREAD

**Issue by Mnikley** [atuinsh/atuin#1982]
### What did you expect to happen?

Sync working without returning an error

### What happened?

I switched from the official api.atuin.sh server to my own, following the documentation. I run a traefik server and atuin with a postgres db in docker-compose. I increased the max_history_length to 16384, the rest is set to the defaults.

Registering and logging in works, and I can see changes in the database, but when trying to sync i get:
```
❯ atuin sync
Error: There was an error with the atuin sync service: Status 413.
If the problem persists, contact the host

Location:
    /home/runner/work/atuin/atuin/atuin-client/src/api_client.rs:171:9
```

Is there something else i can try to import my ~13k entries? My longest history entry is 1245 characters long:
```
❯ atuin history list | awk '{ print length, $0 }' | sort -n -s -r | cut -d" " -f2- | less -S | head -n 1 | wc -c
1245
```

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.2.0
  sync:
    cloud: false
    records: false
    auto_sync: true
    last_sync: 2024-04-27 15:42:54.424677903 +00:00:00
shell:
  name: zsh
  default: unknown
  plugins:
  - atuin
system:
  os: Debian GNU/Linux
  arch: x86_64
  version: '12'
  disks:
  - name: /dev/mapper/glorypc--vg-root
    filesystem: ext4
  - name: /dev/nvme0n1p2
    filesystem: ext2
  - name: /dev/nvme0n1p1
    filesystem: vfat
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ellie** [comment]
Does increasing `max_record_size` fix it for you?

**Comment by Mnikley** [comment]
unfortunately no, i multiplied the default value by 64:
```
max_record_size = 68719476736
```
also, i tested increaseing the page_size from 1100 to:
```
page_size = 2500
```

**Comment by vonProteus** [comment]
on mac the same problem 
```
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.2.0
  sync:
    cloud: false
    records: false
    auto_sync: true
    last_sync: 2024-04-28 5:03:49.001966 +00:00:00
shell:
  name: zsh
  default: zsh
  plugins:
  - atuin
system:
  os: Darwin
  arch: arm64
  version: 14.4.1
  disks:
  - name: Macintosh HD
    filesystem: apfs
  - name: Macintosh HD
    filesystem: apfs
  - name: Macintosh HD
    filesystem: smbfs
```
and 
`ATUIN_LOG=debug atuin sync -f`
```
[2024-04-28T08:59:16Z DEBUG h2::codec::framed_read] received frame=Headers { stream_id: StreamId(97), flags: (0x4: END_HEADERS) }
[2024-04-28T08:59:16Z DEBUG h2::codec::framed_read] received frame=Data { stream_id: StreamId(97), flags: (0x1: END_STREAM) }
Error: There was an error with the atuin sync service: Status 413.
If the problem persists, contact the host

Location:
    /private/tmp/atuin-20240415-5422-dpc6s2/atuin-18.2.0/atuin-client/src/api_client.rs:171:9
```

**Comment by vonProteus** [comment]
on mac the same problem 
```
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.2.0
  sync:
    cloud: false
    records: false
    auto_sync: true
    last_sync: 2024-04-28 5:03:49.001966 +00:00:00
shell:
  name: zsh
  default: zsh
  plugins:
  - atuin
system:
  os: Darwin
  arch: arm64
  version: 14.4.1
  disks:
  - name: Macintosh HD
    filesystem: apfs
  - name: Macintosh HD
    filesystem: apfs
  - name: Macintosh HD
    filesystem: smbfs
```
and 
`ATUIN_LOG=debug atuin sync -f`

```
…
[2024-04-28T08:59:16Z DEBUG h2::codec::framed_read] received frame=Headers { stream_id: StreamId(97), flags: (0x4: END_HEADERS) }
[2024-04-28T08:59:16Z DEBUG h2::codec::framed_read] received frame=Data { stream_id: StreamId(97), flags: (0x1: END_STREAM) }
Error: There was an error with the atuin sync service: Status 413.
If the problem persists, contact the host

Location:
    /private/tmp/atuin-20240415-5422-dpc6s2/atuin-18.2.0/atuin-client/src/api_client.rs:171:9
```

server in k8s 

`server.toml`

```
host = "0.0.0.0"
port = 8888
open_registration = false
db_uri="#DBURI#"
```
