### ISSUE TITLE
[Bug]: `atuin dotfiles alias import` imports control codes as well

### ISSUE THREAD

**Issue by USA-RedDragon** [atuinsh/atuin#1994]
### What did you expect to happen?

I accidentally ran `atuin dotfiles alias import` in Termux. I expected it to not import invalid aliases. 

### What happened?

Running `atuin dotfiles alias import` imported the `neofetch` lines, including the control codes used to format it. Now, `atuin dotfiles alias list` looks like
![image](https://github.com/atuinsh/atuin/assets/13051767/18f0a98a-891a-4d68-8e0a-69b085bbe0d8)

I am able to delete some of them that don't have control characters, i.e. `atuin dotfiles alias delete '  ..  yyyyyyyyyyyyyyyyyyyy  ..'`, but the ones that do remain have control codes that make it quite difficult to remove and breaks the aliases on my other system (`eval "$(atuin init zsh)"` errors with `(eval):120: bad pattern: ^[[18A^[[9999999D^[[35C^[[0m^[[1m^[[32m^[[1mu0_a381^[[0m@^[[32m^[[1mlocalhost^[[0m`). I'm looking for a way to recover this.

### Atuin doctor output

```yaml
atuin:
  version: 18.2.0
  sync:
    cloud: false
    records: true
    auto_sync: true
    last_sync: 2024-05-02 14:11:27.734397214 +00:00:00
shell:
  name: zsh
  default: unknown
  plugins:
  - atuin
system:
  os: Arch Linux
  arch: x86_64
  version: rolling
  disks:
  - name: /dev/mapper/vg-root
    filesystem: btrfs
  - name: /dev/mapper/vg-root
    filesystem: btrfs
  - name: /dev/mapper/vg-root
    filesystem: btrfs
  - name: /dev/nvme1n1p1
    filesystem: vfat
  - name: /dev/nvme2n1
    filesystem: f2fs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
