### ISSUE TITLE
[Bug]: -vgprintf: warning: ignoring excess arguments, starting with ‘duration’

### ISSUE THREAD

**Issue by Proteusiq** [atuinsh/atuin#1996]
### What did you expect to happen?

Not to see a warning at every command I write

### What happened?

I get this message at the end of all my commands: `-vgprintf: warning: ignoring excess arguments, starting with ‘duration’`

### Atuin doctor output

```yaml
atuin:
  version: 18.2.0
  sync: null
shell:
  name: zsh
  default: zsh
  plugins:
  - atuin
system:
  os: Darwin
  arch: arm64
  version: 14.4.1
  disks:
  - name: Macintosh HD
    filesystem: apfs
  - name: Macintosh HD
    filesystem: apfs

-vgprintf: warning: ignoring excess arguments, starting with ‘duration’
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
