### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jamesscottbrown** [atuinsh/atuin#1997]
### What did you expect to happen?

After running the installer script, I expect the config file `.config/atuin/config.toml` to have been created.

### What happened?

The config file (and indeed the `.config/atuin` directory) isn't created until the `atuin` command is run.

This was initially confusing: I was installing clients to use with a self-hosted atuin server, so wanted to edit the `sync_address` setting before running `atuin login`.

### Atuin doctor output

```yaml
I don't think this is relevant, but for one VM I tested this in:


atuin:
  version: 18.2.0
  sync: null
shell:
  name: bash
  default: unknown
  plugins:
  - bash-preexec
system:
  os: Ubuntu
  arch: x86_64
  version: '24.04'
  disks:
  - name: /dev/sda1
    filesystem: ext4
  - name: /dev/sda16
    filesystem: ext4
  - name: /dev/sda15
    filesystem: vfat
  - name: :/home/jsb
    filesystem: fuse.sshfs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
