### ISSUE TITLE
[Bug]: commented commands not shown in history

### ISSUE THREAD

**Issue by chain710** [atuinsh/atuin#1998]
### What did you expect to happen?

Expect same behavior as bash, like:

```
# echo hello
```

You can find this record again using ctrl + r.

### What happened?

Fresh install, can not find commands starts with '#'

### Atuin doctor output

```yaml
atuin:
  version: 18.2.0
  sync: null
shell:
  name: bash
  default: unknown
  plugins:
  - atuin
  - bash-preexec
system:
  os: Debian GNU/Linux
  arch: x86_64
  version: '12'
  disks:
  - name: /dev/sda1
    filesystem: ext4
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
