### ISSUE TITLE
Do not print password in error message on server startup

### ISSUE THREAD

**Issue by yggdr** [atuinsh/atuin#2020]
### What did you expect to happen?

Some filtering on the configured `db_uri` to redact the configured password.

### What happened?

When reinstalling atuin, due to some misconfiguration on my part, it printed this error message on startup:
```
Error: failed to connect to db: PostgresSettings { db_uri: "postgres://atuin:PASSWORD_HERE@10.0.9.105/atuin" }

Caused by:
[…]
```
which included the password.

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics

[Filesystem] ZFS is known to have some issues with SQLite. Atuin uses SQLite heavily. If you are having poor performance, there are some workarounds here: https://github.com/atuinsh/atuin/issues/952

Please include the output below with any bug reports or issues

atuin:
  version: 18.2.0
  sync:
    cloud: false
    records: true
    auto_sync: true
    last_sync: 2024-05-13 12:28:42.386454986 +00:00:00
shell:
  name: 'python: xonsh'
  default: unknown
  plugins:
  - atuin
system:
  os: FreeBSD
  arch: amd64
  version: '14.0'
  disks:
[…]
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
