### ISSUE TITLE
[Bug]: Error: pool timed out while waiting for an open connection

### ISSUE THREAD

**Issue by pmopmo** [atuinsh/atuin#2025]
### What did you expect to happen?

Expect no error message and atuin to continue to work as normal

### What happened?

```
Error: pool timed out while waiting for an open connection

Location:
    atuin/src/command/client.rs:108:18
```

After this error atuin misbehaves in all existing terminals, somtimes it works, somtimes I get an empty list, somtimes nothig, and somtemies weird newlines.

When I start a new terminal it seems to work as expected

os-info below

```
$ cat /etc/os-release
Error: pool timed out while waiting for an open connection

Location:
    atuin/src/command/client.rs:108:18

PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

Additional context: 
  - wsl1
  - Windows Terminal Version: 1.18.231009002-preview    
  - tmux 3.2a
  - windows 10

### Atuin doctor output

```yaml
atuin:
  version: 18.2.0
  sync: null
shell:
  name: bash
  default: unknown
  plugins:
  - atuin
  - bash-preexec
system:
  os: Ubuntu
  arch: x86_64
  version: '22.04'
  disks:
  - name: rootfs
    filesystem: wslfs
  - name: C:\134
    filesystem: drvfs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
