### ISSUE TITLE
[Bug]: stty: 'standard input': unable to perform all requested operations

### ISSUE THREAD

**Issue by xiaozhuai** [atuinsh/atuin#2027]
### What did you expect to happen?

No warnning.

### What happened?

It shows
```
stty: 'standard input': unable to perform all requested operations
```

How to repro:
1. Input `ls -al`
2. Press Enter
3. Press Up
4. Press Enter

But the following is ok with no warning
1. Input `ls -al`
2. Press Enter
3. Press Up
4. Press Tab
5. Press Enter

BTW, I use bash on macOS, and install `bash-preexec` using brew.
```
[ -f /opt/homebrew/etc/profile.d/bash-preexec.sh ] && . /opt/homebrew/etc/profile.d/bash-preexec.sh
eval "$(atuin init bash)"
```

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics

[Shell] If you are using Bash, Atuin requires that either bash-preexec or ble.sh be installed. An older ble.sh may not be detected. so ignore this if you have it set up! Read more here: https://docs.atuin.sh/guide/installation/#bash

Please include the output below with any bug reports or issues

atuin:
  version: 18.2.0
  sync: null
shell:
  name: bash
  default: bash
  plugins:
  - atuin
system:
  os: Darwin
  arch: arm64
  version: '14.5'
  disks:
  - name: MacHD
    filesystem: apfs
  - name: MacHD
    filesystem: apfs
  - name: Backup
    filesystem: apfs
  - name: Share
    filesystem: tuxera_ntfs
  - name: ForMac
    filesystem: hfs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
