### ISSUE TITLE
[Bug]: Invert doesn't invert preview location

### ISSUE THREAD

**Issue by zonorti** [atuinsh/atuin#2038]
### What did you expect to happen?

Config:
```
style = "compact"
invert = true
inline_height = 40
show_preview = true
```

I would expect that preview line is at the top, the same way it works in the non-inverted orientation.

### What happened?

Preview line is at the end of the list, creating a significant visual distance between input and result.

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.2.0
  sync: null
shell:
  name: zsh
  default: zsh
  plugins:
  - atuin
system:
  os: Darwin
  arch: arm64
  version: 14.4.1
  disks:
  - name: Macintosh HD
    filesystem: apfs
  - name: Macintosh HD
    filesystem: apfs
  - name: Fedora Linux with GNOME
    filesystem: apfs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
