### ISSUE TITLE
[Bug]: pool timed out while waiting for an open connection

### ISSUE THREAD

**Issue by stkw0** [atuinsh/atuin#2040]
### What did you expect to happen?

atuin should be more performant in temporary high IO pressure conditions. For example, by writing to a temporary buffer before writing to the DB, which allows reducing the latency imposed by atuin and working more smoothly even in bad conditions.

### What happened?

It timed out

### Atuin doctor output

```yaml
atuin:
  version: 18.2.0
  sync: null
shell:
  name: zsh
  default: unknown
  plugins:
  - atuin
system:
  os: Gentoo
  arch: x86_64
  version: '2.15'
  disks:
  - name: /dev/sdc1
    filesystem: btrfs
  - name: /dev/sdb1
    filesystem: btrfs
  - name: /dev/nvme0n1p1
    filesystem: btrfs
  - name: /dev/sdb3
    filesystem: btrfs
  - name: /dev/sdb3
    filesystem: btrfs
  - name: /dev/sdb1
    filesystem: btrfs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
