### ISSUE TITLE
[Bug]: Missing `ATUIN_SESSION` env-var spam

### ISSUE THREAD

**Issue by Nemo157** [atuinsh/atuin#2042]
### What did you expect to happen?

The atuin client should probably set itself up even if it fails to connect to the daemon and periodically retry connecting

### What happened?

When I opened a new shell there was an error I assume connecting to the daemon:

```
Error: pool timed out while waiting for an open connection

Location:
    crates/atuin/src/command/client.rs:117:18
```

After that, whenever I typed in the shell and triggered the `atuin` based auto-completion it logged:

```
ERROR: Failed to find $ATUIN_SESSION in the environment. Check that you have correctly set up your shell.
```

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics

[Filesystem] ZFS is known to have some issues with SQLite. Atuin uses SQLite heavily. If you are having poor performance, there are some workarounds here: https://github.com/atuinsh/atuin/issues/952

Please include the output below with any bug reports or issues

atuin:
  version: 18.2.0
  sync:
    cloud: false
    records: false
    auto_sync: true
    last_sync: 2024-05-25 8:15:31.388708193 +00:00:00
shell:
  name: zsh
  default: zsh
  plugins: []
  preexec: null
system:
  os: i use arch, btw
  arch: x86_64
  version: '23.11'
  disks:
  - name: rpool/nixos/root
    filesystem: zfs
  ... a lot more irrelevant zfs file systems ...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ellie** [comment]
```
Error: pool timed out while waiting for an open connection
```

This error comes from writing to sqlite, and is unrelated to the daemon. It should not be happening if the daemon is enabled. Can you confirm via the daemon logs that it is being used for history storage? 

```
ERROR: Failed to find $ATUIN_SESSION in the environment. Check that you have correctly set up your shell.
```

That env var is initialized to the output of `atuin uuid` when your shell starts. If it is not there, there's something funky going on with your shell setup.

I can see from `atuin doctor` that the Atuin shell plugin is not setup

**Comment by Nemo157** [comment]
Ah, that `atuin doctor` was from the broken shell, from one that initialized correctly it has

```
shell:
  name: zsh
  default: zsh
  plugins:
  - atuin
  preexec: built-in
```
