### ISSUE TITLE
[Bug]: Missing entries in interactive search

### ISSUE THREAD

**Issue by arnfaldur** [atuinsh/atuin#2048]
### What did you expect to happen?

Within nushell, when I invoke the interactive atuin search using C-r, I expect to be able to find old entries.
The cutoff seems to be from the entries that I imported from xonsh-sqlite.

### What happened?

It doesn't show them.

I can see the entries in the atuin `history.db` file, so they're there. 

`atuin search` also shows these entries. `atuin search -i` doesn't however. There are ~42k entries in the history. The interactive prompt counts these correctly.

I only found an issue with a similar thing happening on zsh/bash but that was resolved with an update. Updating from the main branch, tagged 0.18.1 to the official 0.18.2 release had no effect on this issue.

### Atuin doctor output

```yaml
atuin:
  version: 18.2.0
  sync: null
shell:
  name: nu
  default: unknown
  plugins:
  - atuin
system:
  os: Arch Linux
  arch: x86_64
  version: unknown

I'd rather not share my disk layout.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
