### ISSUE TITLE
[Bug]: Maybe filter out fish's `env` from `atuin stats`?

### ISSUE THREAD

**Issue by philn** [atuinsh/atuin#2055]
### What did you expect to happen?

`atuin stats` not showing `env` in my top 5 ;) Usually to run a process with env vars in fish you have to use the `env` command, so something like `env FOO=bar thecommand`... Could atuin detect this and account for `thecommand` instead of `env` when generating stats?

### What happened?

`env` in top commands of `atuin stats`

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.2.0
  sync:
    cloud: true
    records: false
    auto_sync: true
    last_sync: 2024-05-29 19:18:43.907793712 +00:00:00
shell:
  name: fish
  default: unknown
  plugins:
  - atuin
system:
  os: Fedora Linux
  arch: x86_64
  version: '40'
  disks:
  - name: /dev/mapper/fedora-root
    filesystem: ext4
  - name: /dev/mapper/fedora-root
    filesystem: ext4
  - name: /dev/mapper/fedora-root
    filesystem: ext4
  - name: /dev/mapper/fedora-root
    filesystem: ext4
  - name: /dev/nvme0n1p2
    filesystem: ext4
  - name: /dev/nvme0n1p1
    filesystem: vfat
  - name: /dev/mapper/fedora-home
    filesystem: ext4
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
