### ISSUE TITLE
[Bug]: cargo fallback setup method sources cargo env in .profile

### ISSUE THREAD

**Issue by funkyfisch** [atuinsh/atuin#2071]
### What did you expect to happen?

After adding the `eval $(atuin init bash)` to my bashrc file, it should work fine in all future bash sessions

### What happened?

When falling back to the cargo installation method (which builds the whole project), a line inside ~/.profile is added, but _after_ the .bashrc file is sourced. Which means that if my .bashrc file has the above eval line somewhere, it will fail because atuin wont be recognized _until_ the cargo env is sourced.

This was caught on a RPI4 installation which is different from typical ubuntu installations

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics

[Shell] If you are using Bash, Atuin requires that either bash-preexec or ble.sh be installed. An older ble.sh may not be detected. so ignore this if you have it set up! Read more here: https://docs.atuin.sh/guide/installation/#bash

Please include the output below with any bug reports or issues

atuin:
  version: 18.2.0
  sync: null
shell:
  name: bash
  default: unknown
  plugins:
  - atuin
system:
  os: Debian GNU/Linux
  arch: aarch64
  version: '12'
  disks:
  - name: /dev/mmcblk0p2
    filesystem: ext4
  - name: /dev/mmcblk0p1
    filesystem: vfat

I do have blesh installed in a correct way
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
