### ISSUE TITLE
[Bug]:  (code: 261) database is locked on statup

### ISSUE THREAD

**Issue by UbiquitousPhoton** [atuinsh/atuin#2082]
### What did you expect to happen?

Atuin starts up on multiple sessions at the same time with no issues.

### What happened?

So, to preface: I currently have two machines on which I am running Atuin: One with /home mounted on spinning rust as ext4 (don't judge me), and one where /home is mounted on ssd as btrfs
As part of startup I am launching Zellij within Kitty, which spins up 16 panes

Pre background daemon, this (seemed) to work fine. Post it, on the spinning rust machine (and occasionally on the ssd one) I would get timeouts locking the database.

Ok, all good, I will increase the timeout...

With the increased timeout, now I get basically one pane starting up ok, but all the others throw the above error:

> Error: error returned from database: (code: 261) database is locked
> 
> Caused by:
>     (code: 261) database is locked
> 
> Location:
>     atuin/src/command/client.rs:108:18

(Just as a side note, this used to sometimes cause issues with McFly too)

I will note that this is a relatively 'old' installation, so its quite possible I did not migrate something. I'm using local sync, but have been contemplating running my own server - would this actually help things, as I suspect it might?

### Atuin doctor output

```yaml
(The successful pane)

Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.2.0
  sync: null
shell:
  name: fish
  default: unknown
  plugins:
  - atuin
system:
  os: Manjaro Linux
  arch: x86_64
  version: 24.0.1
  disks:
  - name: /dev/nvme0n1p2
    filesystem: ext4
  - name: systemd-1
    filesystem: autofs
  - name: systemd-1
    filesystem: autofs
  - name: systemd-1
    filesystem: autofs
  - name: systemd-1
    filesystem: autofs
  - name: /dev/nvme0n1p1
    filesystem: vfat
  - name: /dev/sdb1
    filesystem: ext4
  - name: /dev/sdc1
    filesystem: ext4
  - name: /dev/sda1
    filesystem: ext4
  - name: /dev/sdd2
    filesystem: fuseblk
  - name: pCloud.fs
    filesystem: fuse

a failed pane:

Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.2.0
  sync: null
shell:
  name: fish
  default: unknown
  plugins: []
system:
  os: Manjaro Linux
  arch: x86_64
  version: 24.0.1
  disks:
  - name: /dev/nvme0n1p2
    filesystem: ext4
  - name: systemd-1
    filesystem: autofs
  - name: systemd-1
    filesystem: autofs
  - name: systemd-1
    filesystem: autofs
  - name: systemd-1
    filesystem: autofs
  - name: /dev/nvme0n1p1
    filesystem: vfat
  - name: /dev/sdb1
    filesystem: ext4
  - name: /dev/sdc1
    filesystem: ext4
  - name: /dev/sda1
    filesystem: ext4
  - name: /dev/sdd2
    filesystem: fuseblk
  - name: pCloud.fs
    filesystem: fuse
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
