### ISSUE TITLE
[Bug]: ctrl + left arrow key does not work anymore

### ISSUE THREAD

**Issue by Handkep** [atuinsh/atuin#2086]
### What did you expect to happen?

it would be nice if the navigation via ctrl + arrow key to skip words would work with atuin installed

### What happened?

after a fresh installation of atuin, skipping words via ctrl + arrow key does not work anymore. If i disable atuin in the .zshrc file, it works like before.
note:
this issue is on my surface only. It works like a charm on my main pc. On both, Suface and main pc is WSL2 with zsh installed.

(could the bluetooth keyboard be the problem?)

### Atuin doctor output

```yaml
atuin:
  version: 18.2.0
  sync:
    cloud: true
    records: true
    auto_sync: true
    last_sync: 2024-05-31 23:01:05.003232181 +00:00:00
shell:
  name: zsh
  default: unknown
  plugins:
  - atuin
system:
  os: Ubuntu
  arch: x86_64
  version: '22.04'
  disks:
  - name: none
    filesystem: 9p
  - name: none
    filesystem: overlay
  - name: /dev/sdc
    filesystem: ext4
  - name: /dev/sdc
    filesystem: ext4
  - name: none
    filesystem: overlay
  - name: none
    filesystem: overlay
  - name: none
    filesystem: overlay
  - name: C:\134
    filesystem: 9p
  - name: /dev/sdc
    filesystem: ext4
  - name: snapfuse
    filesystem: fuse.snapfuse
  - name: snapfuse
    filesystem: fuse.snapfuse
  - name: snapfuse
    filesystem: fuse.snapfuse
  - name: snapfuse
    filesystem: fuse.snapfuse
  - name: snapfuse
    filesystem: fuse.snapfuse
  - name: snapfuse
    filesystem: fuse.snapfuse
  - name: snapfuse
    filesystem: fuse.snapfuse
  - name: snapfuse
    filesystem: fuse.snapfuse
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
