### ISSUE TITLE
[Bug]: atuin store --help is missing explanations

### ISSUE THREAD

**Issue by SuperSandro2000** [atuinsh/atuin#2095]
### What did you expect to happen?

Many subcommands have good help texts like atuin account:

```
Manage your sync account

Usage: atuin account <COMMAND>

Commands:
  login            Login to the configured server
  register
  logout           Log out
  delete           Delete your account, and all synced data
  change-password  Change your password
  help             Print this message or the help of the given subcommand(s)

Options:
  -h, --help  Print help
```

### What happened?

But atuin store does not:

```
 ➜ atuin store
Manage the atuin data store

Usage: atuin store <COMMAND>

Commands:
  status
  rebuild
  rekey
  purge
  verify
  push
  pull
  help     Print this message or the help of the given subcommand(s)

Options:
  -h, --help  Print help
```

I was searching for atuin purge but couldn't find it and first thought it would delete literally everything.

Also the help for that is rather plain

``` 
 ➜ atuin store purge --help
Usage: atuin store purge

Options:
  -h, --help  Print help
```

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics

[Filesystem] ZFS is known to have some issues with SQLite. Atuin uses SQLite heavily. If you are having poor performance, there are some workarounds here: https://github.com/atuinsh/atuin/issues/952

Please include the output below with any bug reports or issues

atuin:
  version: 18.2.0
  sync:
    cloud: false
    records: true
    auto_sync: true
    last_sync: 2024-06-06 23:35:10.916150049 +00:00:00
shell:
  name: bash
  default: bash
  plugins:
  - atuin
  - bash-preexec
  preexec: bash-preexec
system:
  os: NixOS
  arch: x86_64
  version: '24.11'
  disks:
....
```

I know about zfs and that is soon to be fixed by the daemon
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
