### ISSUE TITLE
[Bug]: cargo-binstall falls back to installing from source

### ISSUE THREAD

**Issue by senekor** [atuinsh/atuin#2111]
### What did you expect to happen?

cargo-binstall should install the prebuilt binaries from the GitHub releases page.

### What happened?

It fell back to installing from source (which itself failed (because of atuin-daemon's protobuf))

### Atuin doctor output

```yaml
atuin:
  version: 18.2.0
  sync: null
shell:
  name: fish
  default: unknown
  plugins:
  - atuin
system:
  os: Fedora Linux
  arch: x86_64
  version: '40'
  disks:
  - name: /dev/mapper/luks-72cdd264-01e0-4bf2-a721-44c9ccc5c1f6
    filesystem: btrfs
  - name: /dev/mapper/luks-72cdd264-01e0-4bf2-a721-44c9ccc5c1f6
    filesystem: btrfs
  - name: /dev/nvme0n1p2
    filesystem: ext4
  - name: /dev/nvme0n1p1
    filesystem: vfat
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
