### ISSUE TITLE
[Bug]: Synchronization on new device doesn't work, atuin can't decrypt it's own database (Failed to verify local store encryption: attempting to decrypt with incorrect key.)

### ISSUE THREAD

**Issue by pacjo** [atuinsh/atuin#2142]
### What did you expect to happen?

I'd like to have everything just work? I don't know, keys are the same, didn't have any issues with atuin untill I needed to reinstall the os on my main pc.

### What happened?

My drive died and I needed a reinstall on my main pc. I'm using nixos on my laptop and decided that it's finally time to migrate to nix on my desktop. Used parts of the same config (the same shell configuration, packages, different hostnames if it matters).

At first I didn't have history on my pc (tried `sync -f`, re-logging, nothing (I did verify both keys are the same)). After searching issues I found some promising commands: `atuin store verify` and `atuin store rebuild history`. Neither showed anything bad, but after syncing I still lacked history on the pc.
Looking through help I found `atuin store push / pull`, hoping it would fix my issues I run push on the laptop (where everything worked).

Running it was promising, then pull on the pc got part of history (or maybe it's everything, I'm a bit lost right now). Fianlly push from the pc (hoping everything would be merged), pulling on the laptop and here we are - with only a part of history on the "new" machine and most missing on the "old" one.

`atuin stats` still shows correct looking numbers on the laptop ("old") and incorrect on the pc ("new"). 

Is there any hope of recovering from this disaster and getting the data back?

Also I now get this on the "old" machine:
```
~ ❯ atuin store rebuild history
Error: attempting to decrypt with incorrect key. currently using <key1>, expecting <key2>

Location:
    crates/atuin-client/src/record/encryption.rs:132:9


~ ❯ atuin store verify
Verifying local store can be decrypted with the current key
Failed to verify local store encryption: attempting to decrypt with incorrect key. currently using <key1>, expecting <key2>

Location:
    crates/atuin-client/src/record/encryption.rs:132:9

took 3m48s 
~ ❯
```

### Atuin doctor output

```yaml
pc ("new"):

~ ❯ atuin doctor
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-06-14 19:06:58.191075081 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "nu",
    "default": "bash",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "NixOS",
    "arch": "x86_64",
    "version": "24.05",
    "disks": [
      {
        "name": "/dev/disk/by-uuid/6eb431ae-1779-4940-b2bf-e72985a23456",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/disk/by-uuid/6eb431ae-1779-4940-b2bf-e72985a23456",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}



laptop ("old"):
~ ❯ atuin doctor
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": false,
      "auto_sync": true,
      "last_sync": "2024-06-14 18:52:32.35645073 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "nu",
    "default": "bash",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "NixOS",
    "arch": "x86_64",
    "version": "24.05",
    "disks": [
      {
        "name": "/dev/disk/by-uuid/4f1116ad-b95d-4e37-bb18-e4dba2b4b597",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/disk/by-uuid/4f1116ad-b95d-4e37-bb18-e4dba2b4b597",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sda1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
