### ISSUE TITLE
[Bug]: Recover account / sync problems

### ISSUE THREAD

**Issue by Valshie** [atuinsh/atuin#2143]
### What did you expect to happen?

Sync between my computer and laptop

### What happened?

I installed atuin on both my computer and laptop, but the sync wasn't working as described here: https://github.com/atuinsh/atuin/issues/2142

I tried following the steps on the thread and nothing worked. After that I tried to do a clean reinstall and remake my account, I did that few times to see if the bug would be fixed, but it didn't, and in one of the delete/remake account processes, I might've entered my password wrong and now I don't have access to my account anymore in neither of them.

And while I know the user/login and it has an email which I could recover the password from, I see no recovery function or way to do so.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Arch Linux",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme1n1p2",
        "filesystem": "fuseblk"
      },
      {
        "name": "/dev/sdc2",
        "filesystem": "fuseblk"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/sdb2",
        "filesystem": "fuseblk"
      },
      {
        "name": "/dev/sda2",
        "filesystem": "fuseblk"
      },
      {
        "name": "/dev/sdd1",
        "filesystem": "fuseblk"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
