### ISSUE TITLE
[Bug]: sync_frequency = "0" never syncs

### ISSUE THREAD

**Issue by heftig** [atuinsh/atuin#2147]
### What did you expect to happen?

Atuin syncs after every command.

### What happened?

Atuin never syncs. A manual sync using `atuin sync` still works, as does using `"1s"` as the frequency.

I suspect this broke in 18.3.0.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-06-17 6:41:34.445861124 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Arch Linux",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
      {
        "name": "/dev/mapper/cornicle-root",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
