### ISSUE TITLE
[Bug]: cmd+up-arrow disables up-arrow functionality for current prompt

### ISSUE THREAD

**Issue by injust** [atuinsh/atuin#2165]
### What did you expect to happen?

The up-arrow binding should always work.

### What happened?

I accidentally pressed cmd+up-arrow, which gave me the standard fish shell up-arrow behaviour.

I couldn't get back the atuin up-arrow behaviour until I hit enter (to get a new prompt) or ran a command (e.g. `true`).

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "x86_64",
    "version": "14.5",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
