### ISSUE TITLE
[Bug]: URGENT system locking, uninstall or at a minimum disable when installed using CURL? 

### ISSUE THREAD

**Issue by Free-Radical** [atuinsh/atuin#2169]
### What did you expect to happen?

Not sure if Atuin is the reason but  machine is locking up and as part of debugging I need to be able to remove new packages including atuin, ASAP.

FYI: installed atuin in an ubuntu distobox, exported atuin to host system, Fedora Silverblue 40, atuin possibly locking whole machine

### What happened?

installed atuin using-

/bin/bash -c "$(curl --proto '=https' --tlsv1.2 -sSf https://setup.atuin.sh)"

machine is locking up intermittently.

I CANT FIND INSTRUCTIONS TO REMOVE/UNINSTALL/DISABLE when installed using the bash/curl option.

I read the comments about uninstalling but seriously you have to come up with a better option than "Depends upon how user installed". It looks like an awesome utility but not having clear uninstall instructions is a serious issue, especially cause I now have to fill out a bug report and wait for the answer.

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "22.04",
    "disks": [
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "overlay",
        "filesystem": "overlay"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sda1",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc4",
        "filesystem": "btrfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
