### ISSUE TITLE
[Bug]: Deleted commands don't stay deleted

### ISSUE THREAD

**Issue by jbellis** [atuinsh/atuin#2178]
### What did you expect to happen?

After deleting commands from history, they should stay gone next time I hit ctrl-r

### What happened?

ctrl-r exec:java [5 results]
ctrl-o ctrl-d, for 4 results [only 1 result now visible]
esc

ctrl-r exec:java [5 results]

### Atuin doctor output

```yaml
$ atuin doctor
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-06-21 20:21:56.851349026 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": null
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "20.04",
    "disks": [
      {
        "name": "/dev/nvme0n1p3",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/sda1",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdb2",
        "filesystem": "ext4"
      }
    ]
  }
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
