### ISSUE TITLE
[Bug]:  ctrl-r not rebinded with `--disable-up-arrow`

### ISSUE THREAD

**Issue by rawnly** [atuinsh/atuin#2180]
### What did you expect to happen?

To have `ctrl-r` rebinded

### What happened?

It's not rebinding `ctrl-r` when passing `--disable-up-arrow`

My zshrc

```
...
eval "$(atuin init zsh --disable-up-arrow)"
eval "$(atuin gen-completions --shell zsh)"
...
```

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "no last sync"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "14.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
