### ISSUE TITLE
Unable to resolve `.local` address using docker on pi

### ISSUE THREAD

**Issue by deepanchal** [atuinsh/atuin#2192]
## Description

I'm encountering an issue with Atuin running on my Raspberry Pi using Docker. When accessing Atuin through the local IP address (e.g., 192.168.0.90), it works perfectly. However, it fails when trying to connect using the `.local` address.

```sh
❯ curl http://beacon.local:8888/sync/status
{"reason":"missing authorization header"}                                                                       

❯ atuin status
Error: error sending request for url (http://beacon.local:8888/sync/status): error trying to connect: operation timed out

Caused by:
   0: error trying to connect: operation timed out
   1: operation timed out

Location:
    /build/source/atuin-client/src/api_client.rs:225:20
```

## Steps to Reproduce:

- Set up Atuin on a Raspberry Pi using Docker.

Here's my `docker-compose.yml`:

```yaml
services:
  atuin:
    restart: always
    image: ghcr.io/atuinsh/atuin:18.2.0
    command: server start
    volumes:
      - "./config:/config"
    links:
      - postgresql:db
    ports:
      - 8888:8888
    user: "0:0"
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: postgres://$ATUIN_DB_USERNAME:$ATUIN_DB_PASSWORD@db/$ATUIN_DB_NAME
      RUST_LOG: info,atuin_server=debug
  postgresql:
    image: postgres:14
    restart: unless-stopped
    volumes: # Don't remove permanent storage for index database files!
      - "./database:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      POSTGRES_DB: ${ATUIN_DB_NAME}
```

- Use a local IP address to verify connectivity.
- Attempt to connect using the `<YOUR_PI_HOSTNAME>.local` address (`beacon.local` in this case).

## Environment Details

Atuin version: 18.2.0
Docker version: Docker version 26.1.4, build 5650f9b
Docker compose version: Docker Compose version v2.27.1
Raspberry Pi model and OS: Raspberry Pi 4 Model B Rev 1.4 8GB RAM running Raspberry Pi OS Lite

Atuin doctor output:
```
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.2.0
  sync:
    cloud: false
    records: false
    auto_sync: true
    last_sync: 2024-06-24 18:18:51.051533645 +00:00:00
shell:
  name: zsh
  default: unknown
  plugins:
  - atuin
system:
  os: Manjaro Linux
  arch: x86_64
  version: 24.0.2
  disks:
  - name: /dev/nvme1n1p4
    filesystem: btrfs
  - name: /dev/nvme1n1p4
    filesystem: btrfs
  - name: /dev/nvme1n1p4
    filesystem: btrfs
  - name: /dev/nvme1n1p4
    filesystem: btrfs
  - name: /dev/nvme1n1p4
    filesystem: btrfs
  - name: /dev/nvme1n1p4
    filesystem: btrfs
  - name: /dev/nvme1n1p4
    filesystem: btrfs
  - name: /dev/nvme1n1p1
    filesystem: vfat
  - name: /dev/nvme1n1p4
    filesystem: btrfs
  - name: /dev/nvme1n1p4
    filesystem: btrfs
  - name: /dev/nvme1n1p4
    filesystem: btrfs
  - name: /dev/nvme1n1p4
    filesystem: btrfs
  - name: /dev/nvme1n1p4
    filesystem: btrfs
  - name: /dev/nvme1n1p4
    filesystem: btrfs
  - name: /dev/nvme1n1p4
    filesystem: btrfs
  - name: /dev/nvme1n1p4
    filesystem: btrfs
  - name: /dev/nvme1n1p4
    filesystem: btrfs
```
