### ISSUE TITLE
[Bug]: Failed to sync; attempting to decrypt with incorrect key

### ISSUE THREAD

**Issue by PerynFr** [atuinsh/atuin#2197]
### What did you expect to happen?

I was expecting synchronization, the password was created, login was successful, but an error occurred during synchronization

╰─❯ atuin sync                                                                                                                           ─╯
Uploading 8 records to 01904e75bcbb752da18f46d5eb1400e8/history
  [00:00:00] [##################################################################################################################] 8/8 (0.0s)9/0 up/down to record store
1133 in history index, but 38 in history store
Running automatic history store init...
Error: attempting to decrypt with incorrect key. currently using k4.lid.EYc1sfVm3F-SXpQncjfurYvsz64edSmVFtJqKdP5SJZp, expecting k4.lid.fIFwT73H69QOlY2ySGY92P_AsWptPibhNrPqHnGcMZeA

Location:
    crates/atuin-client/src/record/encryption.rs:132:9

### What happened?

What can I do?
it didn't help me:
https://forum.atuin.sh/t/sync-v2-testing/124/29?u=ellie

my problem:
```
Local store purge completed OK
╭─     ~/.local/share/atuin                                                                                                  15:57:47 ─╮
╰─❯ atuin store purge                                                                                                                    ─╯
Purging local records that cannot be decrypted
Local store purge completed OK
╭─     ~/.local/share/atuin                                                                                                  15:57:52 ─╮
╰─❯ atuin store verify                                                                                                                   ─╯
Verifying local store can be decrypted with the current key
Local store encryption verified OK
╭─     ~/.local/share/atuin                                                                                                  15:57:59 ─╮
╰─❯ atuin store push                                                                                                                     ─╯
Uploading 10 records to 01904e75bcbb752da18f46d5eb1400e8/history
  [00:00:00] [################################################################################################################] 10/10 (0.0s)Uploaded 11 records
╭─     ~/.local/share/atuin                                                                                                  15:58:07 ─╮
╰─❯ atuin store pull                                                                                                                     ─╯
Downloading 16 records from 01904f2f9c507d2caa56728715de2778/history
  [00:00:00] [################################################################################################################] 16/16 (0.0s)Downloaded 17 records
Error: attempting to decrypt with incorrect key. currently using k4.lid.3gH7OFUMKdteVMvqAtOye6KWsSKZkUM_vwMRRiYXS6v5, expecting k4.lid.fIFwT73H69QOlY2ySGY92P_AsWptPibhNrPqHnGcMZeA

Location:
    crates/atuin-client/src/record/encryption.rs:132:9
╭─     ~/.local/share/atuin    
```

### Atuin doctor output

```yaml
╰─❯ atuin doctor                                                                                                                         ─╯
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-06-25 14:00:10.187958426 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Debian GNU/Linux",
    "arch": "x86_64",
    "version": "12",
    "disks": [
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/sda2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sda1",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
