### ISSUE TITLE
[Bug]: suffix-exact-match doesn't trim command first

### ISSUE THREAD

**Issue by kidonng** [atuinsh/atuin#2198]
### What did you expect to happen?

Searching command with suffix-exact-match (`$`) doesn't trim commands first, making some commands with trailing spaces unsearchable.

### What happened?

Here's a little command in atuin:

<img width="326" alt="Screenshot 2024-06-26 at 1 08 17 AM" src="https://github.com/atuinsh/atuin/assets/44045911/0c9d0a63-f8d5-4627-8eb0-d3a8cada3e09">

You expect `file$` to match it right? Wrong!

<img width="339" alt="Screenshot 2024-06-26 at 1 08 23 AM" src="https://github.com/atuinsh/atuin/assets/44045911/7091a543-21ea-44fb-b15b-2211bed60ad4">

Let's <kbd>Tab</kbd> to see what it _really_ is:

<img width="203" alt="Screenshot 2024-06-26 at 1 08 35 AM" src="https://github.com/atuinsh/atuin/assets/44045911/186f4f70-f7a8-43b0-a377-a4e5718210f8">

Turns out there's a space after the command (why the space is there is beyond me, atuin probably should have trimmed it when it saves the command). Comparing to another "normal" command makes the difference more clear:

<img width="147" alt="Screenshot 2024-06-26 at 1 08 42 AM" src="https://github.com/atuinsh/atuin/assets/44045911/528fb50d-0158-48b8-aa9b-6f891c83469a">

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "14.5",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
