### ISSUE TITLE
[Bug]: Scroll position is not restored when using `inline_height`

### ISSUE THREAD

**Issue by svenstaro** [atuinsh/atuin#2207]
### What did you expect to happen?

After exiting atuin, my terminal remains scrolled all the way up. I would expect the position to be restored to where I entered atuin.

### What happened?

My terminal was scrolled way up, as many lines as `inline_height` defines.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-06-28 20:17:50.083127172 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Arch Linux",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
      {
        "name": "/dev/mapper/cryptroot",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
