### ISSUE TITLE
[Bug]: Nushell integration adds a significant delay before each prompt

### ISSUE THREAD

**Issue by WieeRd** [atuinsh/atuin#2208]
### What did you expect to happen?

Atuin integration with Bash/Zsh did not slow down the shell.
I expected the same with Nushell.

### What happened?

There is a noticeable delay after the invoked command's completion and before the new shell prompt shows up.
Even when running a very simple command like `ls` which takes less than a millisecond.

```
~
❯ atuin history list | lines | length
8795

~
❯ timeit do { atuin history end --exit 0 (atuin history start -- ls) }
243ms 217µs 340ns

~
❯ mv ~/.local/share/atuin/ ~/.local/share/atuin.backup

~
❯ atuin history list | lines | length
1

~
❯ timeit do { atuin history end --exit 0 (atuin history start -- ls) }
20ms 317µs 702ns
```

I have 8.8k history records and `atuin history start` + `atuin history end` pair take around 240ms.
After nuking the DB at `~/.local/share/atuin` that time is reduced to 20ms and the delay is no longer noticeable.

The prompt was instantaneous regardless of the history size on the other shells (Bash/Zsh).
So I assume this has to do with Nushell integration specifically.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "nu",
    "default": "nu",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Arch Linux",
    "arch": "x86_64",
    "version": "unknown",
    "disks": [
      {
        "name": "/dev/nvme0n1p3",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p3",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p3",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p3",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p3",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
