### ISSUE TITLE
[Bug]: Timezone not change in config

### ISSUE THREAD

**Issue by mateuscomh** [atuinsh/atuin#2211]
### What did you expect to happen?

When I changed the config.toml file in the timezone line from local to -03:00, the synchronizations continued to happen with UTC 0

### What happened?

Nothing happend, and the time on sync v2 shows UTC+0.

``` $ date Sat Jun 29 15:02:45 -03 2024 ```

Output atuin status
``` Atuin v18.3.0 - Build rev 9be49e434e549d6b13928b530139b66fef6171f1

[Local]
Sync frequency: 1m
Last sync: 2024-06-29 17:58:37.726486695 +00:00:00
```
config.toml
```## default timezone to use when displaying time
## either "l", "local" to use the system's current local timezone, or an offset
## from UTC in the format of "<+|->H[H][:M[M][:S[S]]]"
## for example: "+9", "-05", "+03:30", "-01:23:45", etc.
 timezone = "-03:00"
```

And i miss this config on documentation

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-06-29 17:57:26.619658258 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Debian GNU/Linux",
    "arch": "x86_64",
    "version": "12",
    "disks": [
      {
        "name": "/dev/mapper/debian-barra",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/mapper/debian-boot",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/mapper/debian-home",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sda1",
        "filesystem": "fuseblk"
      },
      {
        "name": "/dev/sdb1",
        "filesystem": "fuseblk"
      }
    ]
  }
}
```
  
``` 
$ timedatectl show
Timezone=America/Sao_Paulo
LocalRTC=no
CanNTP=yes
NTP=yes
NTPSynchronized=yes
TimeUSec=Sat 2024-06-29 15:01:33 -03
RTCTimeUSec=Sat 2024-06-29 15:01:33 -03
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
