### ISSUE TITLE
[Bug]: Right Alt 2 doesn't type @

### ISSUE THREAD

**Issue by millette** [atuinsh/atuin#2223]
### What did you expect to happen?

I'm using French Canadian keyboard on PopOS (like Ubuntu) and I have to Alt keys on my keyboard. Right Alt 2 doesn't type @ as it does everywhere else.

It write "2" instead of the expected "@".

### What happened?

It just types "2" instead of "@". Result is I can't type "@" in atuin. Something in Atuin is disabling my Right Alt key.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "no last sync"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Pop!_OS",
    "arch": "x86_64",
    "version": "22.04",
    "disks": [
      {
        "name": "/dev/nvme0n1p3",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/nvme1n1p1",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdb1",
        "filesystem": "fuseblk"
      },
      {
        "name": "/dev/sdc1",
        "filesystem": "fuseblk"
      },
      {
        "name": "/dev/sdd1",
        "filesystem": "fuseblk"
      },
      {
        "name": "/dev/sda1",
        "filesystem": "fuseblk"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
