### ISSUE TITLE
[Bug]: History stopped recording

### ISSUE THREAD

**Issue by JamyGolden** [atuinsh/atuin#2227]
### What did you expect to happen?

Show history correctly when I press `UP-Arrow` or `atuin history list`

### What happened?

History stopped at some point in time and won't update. I reinstalled the atuin binary and also removed the `~/.config/atuin` and `~/.local/share/atuin` directories. Same issues afterwards. I've run `atuin login` and `atuin sync` and they have worked correctly.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-07-02 10:49:25.55878 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "14.1.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "projects",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
