### ISSUE TITLE
[Bug]: Install script putting env sourcing in .bash_profile instead of .bashrc

### ISSUE THREAD

**Issue by Colonial-Dev** [atuinsh/atuin#2235]
### What did you expect to happen?

When running the install script via `curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh`, Atuin should add:
```
. "$HOME/.atuin/bin/env"
```

To `.bashrc`, in addition to `.bash_profile` - the latter is only sourced in login shells (like the kind you get on a CTRL-ALT-N TTY) and not interactive shells (like `gnome-terminal` or equivalent.)

### What happened?

Atuin wrote `. "$HOME/.atuin/bin/env"` to `.bash_profile` and `.profile`, which meant the binary path was not getting sourced on interactive shell startup.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "bash-preexec"
    ],
    "preexec": null
  },
  "system": {
    # Specifically, Silverblue - but that shouldn't matter here.
    "os": "Fedora Linux",
    "arch": "x86_64",
    "version": "40",
    "disks": [
      {
        "name": "/dev/mapper/luks-583c6499-0e28-4a9e-8580-87553fe4a99f",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/luks-583c6499-0e28-4a9e-8580-87553fe4a99f",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/luks-583c6499-0e28-4a9e-8580-87553fe4a99f",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/luks-583c6499-0e28-4a9e-8580-87553fe4a99f",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/luks-583c6499-0e28-4a9e-8580-87553fe4a99f",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
