### ISSUE TITLE
[Bug]: UI not working properly when inside a GNU screen session

### ISSUE THREAD

**Issue by Alexgar24** [atuinsh/atuin#2244]
### What did you expect to happen?

I would expect the UI to work just outside the screen session

### What happened?

- UI is printed over the CLI, with all the session being visible.
- UI remains onece it has been used.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "22.04",
    "disks": [
      {
        "name": "drivers",
        "filesystem": "9p"
      },
      {
        "name": "none",
        "filesystem": "overlay"   
      },
      {
        "name": "/dev/sdc",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdc",
        "filesystem": "ext4"
      },
      {
        "name": "none",
        "filesystem": "overlay"   
      },
      {
        "name": "none",
        "filesystem": "overlay"
      },
      {
        "name": "none",
        "filesystem": "overlay"
      },
      {
        "name": "C:\\134",
        "filesystem": "9p"
      },
      {
        "name": "/dev/sdc",
        "filesystem": "ext4"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "/dev/sdc",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
