### ISSUE TITLE
[Bug]: Ctrl-C (or any ctrl+key) does not work after invoking atuin with Ctrl-R

### ISSUE THREAD

**Issue by tessus** [atuinsh/atuin#2256]
### What did you expect to happen?

The commands (keyboard shortcuts, like ctrl-c) should work and not produce an output.

### What happened?

On a few machines I use preexec instead of ble, but for some reason it does no longer seem to work.

I started a session (ssh to a box) and pressed `Ctrl-R` to invoke atuin.
Then I used `ctrl-c` or `Esc` to exit.

After that, I can't invoke atuin anymore or even logout with `Ctrl-D`. All Ctrl-key presses produce escape sequences:

key press | output in terminal
-|-
ctrl-c | 9;5u
ctrl-d | 0;5u
ctrl-r | 4;5u

The following 2 files are available for 7 days (until 2024-07-21):

[.bashrc](https://evermeet.cx/paste/.bashrc.CkP8.txt)
[.bash_profile](https://evermeet.cx/paste/.bash_profile.pAQ6.txt)

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0-beta.1",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-07-14 1:23:20.328803267 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Fedora Linux",
    "arch": "x86_64",
    "version": "40",
    "disks": [
      {
        "name": "/dev/mapper/luks-xxx-xxx-xxx-xxx-xxx",
        "filesystem": "xfs"
      },
      {
        "name": "/dev/xxx",
        "filesystem": "xfs"
      },
      {
        "name": "/dev/mapper/xxx",
        "filesystem": "xfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
