### ISSUE TITLE
[Bug]: History not synced across two machines

### ISSUE THREAD

**Issue by mrnugget** [atuinsh/atuin#2266]
### What did you expect to happen?

I expect that when I run a command on a machine on which I'm logged into my atuin account and then sync, that I can then see that command in the history of the other machine.

### What happened?

What I do is this:

### `machine1`

```bash
# machine 1
machine1 $ atuin status
Atuin v18.3.0 - Build rev

[Local]
Sync frequency: 10m
Last sync: 2024-07-15 7:47:12.783859 +00:00:00
History count: 69074
Deleted history count: 0

[Remote]
Address: https://api.atuin.sh
Username: mrnugget
machine1 $ atuin sync
Sync complete! 67580 items in history database, force: false
machine1 $ atuin sync -f
Sync complete! 68236 items in history database, force: true
machine1 $ ssh machine2
```

### `machine2`

After SSH'ing into `machine2`:

```bash
# machine 2
machine2 $ atuin status
Atuin v18.3.0 - Build rev 9be49e434e549d6b13928b530139b66fef6171f1

[Local]
Sync frequency: 10m
Last sync: 2024-07-15 7:46:22.253075643 +00:00:00
History count: 66110
Deleted history count: 0

[Remote]
Address: https://api.atuin.sh
Username: mrnugget
machine2 $ atuin sync -f
Sync complete! 68115 items in history database, force: true
machine2 $ echo "this is machine2"
this is machine2
machine2 $ echo "this is machine2 again"
this is machine2 again
machine2 $ atuin sync -f
Sync complete! 68119 items in history database, force: true
```

### Back on `machine1` again

On this machine, the commands executed and synced on `machine2` just don't show up:

```bash
# machine1 again
machine1 $ atuin sync -f
Sync complete! 69066 items in history database, force: true
machine1 $ atuin search "this is machine" | tail -n 3
2024-07-15 09:47:58     atuin search "this is machine"  59ms
2024-07-15 09:48:05     atuin search "this is machine" | tail -n 3      0s      93ms
2024-07-15 09:48:23     atuin search "this is machine" | tail -n 3      0s
machine1 $

# repeat a few minutes later:

machine1 $ atuin sync -f
Sync complete! 69701 items in history database, force: true
machine1 $ atuin search "this is machine" | tail -n 3
2024-07-15 09:47:58     atuin search "this is machine"  59ms
2024-07-15 09:48:05     atuin search "this is machine" | tail -n 3      0s      93ms
2024-07-15 09:50:52     atuin search "this is machine" | tail -n 3      0s
```

Obviously this is an example, but I ran into this with `curl` commands etc. that I ran months back on `machine2`.

### Atuin doctor output

```yaml
`machine1`:


atuin doctor
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": false,
      "auto_sync": true,
      "last_sync": "2024-07-15 7:49:52.061341 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "14.2.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

`machine2`:

```
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": false,
      "auto_sync": true,
      "last_sync": "2024-07-15 7:47:04.048320369 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "23.10",
    "disks": [
      {
        "name": "/dev/nvme0n1p3",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/nvme0n1p3",
        "filesystem": "ext4"
      }
    ]
  }
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
