### ISSUE TITLE
Systemd file not working

### ISSUE THREAD

**Issue by sascha-wi** [atuinsh/atuin#2280]
### What did you expect to happen?

Easy to set up atuin self-hosted server

### What happened?

When starting the server it gives gibberish error:
`(atuin)[38065]: atuin-server.service: Failed at step NAMESPACE spawning atuin: No such file or directory
(atuin)[545]: atuin-server.service: Failed to set up mount namespacing: /run/systemd/unit-root/etc/atuin: No such file or directory`

```bash
cat /etc/systemd/system/atuin-server.service
[Unit]
Description=Start the Atuin server syncing service
After=network-online.target
Wants=network-online.target systemd-networkd-wait-online.service

[Service]
ExecStart=atuin server start
Restart=on-failure
User=atuin
Group=atuin

Environment=ATUIN_CONFIG_DIR=/etc/atuin
ReadWritePaths=/etc/atuin

# Hardening options
CapabilityBoundingSet=
AmbientCapabilities=
NoNewPrivileges=true
ProtectHome=true
ProtectSystem=strict
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
PrivateTmp=true
PrivateDevices=true
LockPersonality=true

[Install]
WantedBy=multi-user.target
```

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Debian GNU/Linux",
    "arch": "x86_64",
    "version": "12",
    "disks": [
      {
        "name": "/dev/vda1",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
