### ISSUE TITLE
[Bug]: skim search syntax is not interpreted

### ISSUE THREAD

**Issue by viluon** [atuinsh/atuin#2292]
### What did you expect to happen?

Using the [skim search syntax](https://github.com/lotabout/skim?tab=readme-ov-file#search-syntax) will apply exclusions, exact matches, and other features to the search query.

### What happened?

skim's special operators like `'`, `'`, and `$` are not interpreted as operators. They are matched as literal characters to search for instead.
![image](https://github.com/user-attachments/assets/bd39df6e-8965-408a-8c3d-e714e9e3912e)
![image](https://github.com/user-attachments/assets/cc7998a3-4a15-4bf2-b8ae-bd33e93d4bfa)
![image](https://github.com/user-attachments/assets/02eb9750-d711-4e6d-b36f-0ef44dfbe23a)
![image](https://github.com/user-attachments/assets/a25f3bc1-5c84-4bf5-8181-82899fb8d229)

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.2.0
  sync:
    cloud: true
    records: true
    auto_sync: true
    last_sync: 2024-07-18 8:31:48.320016081 +00:00:00
shell:
  name: bash
  default: unknown
  plugins:
  - atuin
  - bash-preexec
system:
  os: Ubuntu
  arch: x86_64
  version: '22.04'
  disks:
  - name: /dev/mapper/vgubuntu-root
    filesystem: ext4
  - name: /dev/nvme0n1p2
    filesystem: ext4
  - name: /dev/nvme0n1p1
    filesystem: vfat
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
