### ISSUE TITLE
[Bug]: 'atuin search -i' only returns entry to the console but doesn't execute it

### ISSUE THREAD

**Issue by acmodeu** [atuinsh/atuin#2308]
### What did you expect to happen?

When I run 'atuin search -i' I'm not able neither to pass the commandtext to the console by pressing 'Tab' nor to execute it by pressing 'Enter'.

### What happened?

 Looks like atuin just echoes it. See attached gif for visual explanation.
 
![Peek 2024-07-25 14-21](https://github.com/user-attachments/assets/770f97ea-7d98-4d4a-87ac-15be3fd28218)

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "blesh"
    ],
    "preexec": "blesh-0.4.0-devel4+fcbf1ed0"
  },
  "system": {
    "os": "Manjaro Linux",
    "arch": "x86_64",
    "version": "24.0.4",
    "disks": [
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
