### ISSUE TITLE
[Bug]: How to bind keys

### ISSUE THREAD

**Issue by Jackwew** [atuinsh/atuin#2317]
### What did you expect to happen?

Unable to bind up-arrow

### What happened?

Unable to bind up-arrow

After installing Autin using Cargo, it defaults to using Ctrl+R to wake it up, and cannot be awakened using Up Arrow

I hope you can answer my question. Thank you

Best wishes

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-07-27 13:51:00.396108633 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Debian GNU/Linux",
    "arch": "x86_64",
    "version": "12",
    "disks": [
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "overlay",
        "filesystem": "overlay"
      },
      {
        "name": "overlay",
        "filesystem": "overlay"
      },
      {
        "name": "overlay",
        "filesystem": "overlay"
      },
      {
        "name": "overlay",
        "filesystem": "overlay"
      },
      {
        "name": "overlay",
        "filesystem": "overlay"
      },
      {
        "name": "overlay",
        "filesystem": "overlay"
      },
      {
        "name": "overlay",
        "filesystem": "overlay"
      },
      {
        "name": "overlay",
        "filesystem": "overlay"
      },
      {
        "name": "overlay",
        "filesystem": "overlay"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
