### ISSUE TITLE
[Bug]: Error: pool timed out while waiting for an open connection

### ISSUE THREAD

**Issue by idvorkin** [atuinsh/atuin#2328]
### What did you expect to happen?

It just works ...

### What happened?

I saw in the linked bugs this is timeout based (https://github.com/atuinsh/atuin/issues/2025), can I debug what is causing this in more details? 

What's interesting, and very likely related is this only happens in tmux after some time (unclear how long it takes - hours?), and it once it starts happening it happens in all tmux sessions.  Once I restart tmux it's fine. If I create a new shell not in tmux it is fine. 

Not sure if it's useful but, my zsh profile: 

<img width="1199" alt="image" src="https://github.com/user-attachments/assets/4a337d79-226c-45d3-bdfa-ddd190e757ac">

I also have lots of disk space

<img width="1028" alt="image" src="https://github.com/user-attachments/assets/368dfb08-a89b-4822-88b0-40c1a78b6d46">

### Atuin doctor output

```yaml
❯ atuin doctor
Error: pool timed out while waiting for an open connection

Location:
    atuin/src/command/client.rs:108:18
Error: pool timed out while waiting for an open connection

Location:
    atuin/src/command/client.rs:108:18

-- 

From another terminal (not in tmux):

Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

atuin:
  version: 18.2.0
  sync: null
shell:
  name: zsh
  default: zsh
  plugins:
  - atuin
system:
  os: Darwin
  arch: arm64
  version: '14.5'
  disks:
  - name: Macintosh HD
    filesystem: apfs
  - name: Macintosh HD
    filesystem: apfs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
