### ISSUE TITLE
[Bug]: atuin status  with Error: the 'year' component could not be parsed

### ISSUE THREAD

**Issue by engeir** [atuinsh/atuin#2336]
### What did you expect to happen?

I ran the `atuin status` command and expected info about my username among other things.

### What happened?

```console
$ atuin status
Error: the 'year' component could not be parsed

Caused by:
    the 'year' component could not be parsed

Location:
    /home/een023/.cargo/registry/src/index.crates.io-6f17d22bba15001f/atuin-client-18.3.0/src/settings.rs:513:27
```

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "no last sync"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "fish",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "22.04",
    "disks": [
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "BoxSync:",
        "filesystem": "fuse.rclone"
      },
      {
        "name": "onedrive:",
        "filesystem": "fuse.rclone"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
