### ISSUE TITLE
[Bug]: Scrolling in tmux window invokes Atuin history panel

### ISSUE THREAD

**Issue by lemorage** [atuinsh/atuin#2338]
### What did you expect to happen?

I expected to be able to scroll within a tmux window without triggering the Atuin history panel. The Atuin history search should not be invoked when scrolling.

### What happened?

When I scroll within a tmux window, the Atuin history panel is automatically invoked. As a result, I can't even see the previous command output by scrolling up. I wonder if there is a walkaround for that?

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": false,
      "auto_sync": true,
      "last_sync": "2024-08-02 13:16:28.349833 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "14.5",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
