### ISSUE TITLE
[Bug]: Defaults to fish and conf.d ? 

### ISSUE THREAD

**Issue by orsenthil** [atuinsh/atuin#2340]
### What did you expect to happen?

I expect atuin to install and setup the configuration

### What happened?

```
(.venv) (base) ➜  todo git:(main) ✗ curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh
 _______  _______  __   __  ___   __    _
|   _   ||       ||  | |  ||   | |  |  | |
|  |_|  ||_     _||  | |  ||   | |   |_| |
|       |  |   |  |  |_|  ||   | |       |
|       |  |   |  |       ||   | |  _    |
|   _   |  |   |  |       ||   | | | |   |
|__| |__|  |___|  |_______||___| |_|  |__|

Magical shell history

Atuin setup
https://github.com/atuinsh/atuin
https://forum.atuin.sh

Please file an issue or reach out on the forum if you encounter any problems!

===============================================================================

downloading atuin 18.3.0 x86_64-apple-darwin
installing to /Users/senthil/.atuin/bin
  atuin
  atuin-update
everything's installed!
mkdir: /Users/senthil/.config/fish/conf.d: Permission denied
ERROR: command failed: mkdir -p /Users/senthil/.config/fish/conf.d
```

### Atuin doctor output

```yaml
~/.atuin/bin/atuin doctor
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [],
    "preexec": null
  },
  "system": {
    "os": "Darwin",
    "arch": "x86_64",
    "version": "13.6.7",
    "disks": [
      {
        "name": "Untitled",
        "filesystem": "apfs"
      },
      {
        "name": "Untitled",
        "filesystem": "apfs"
      }
    ]
  }
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
