### ISSUE TITLE
[Bug]: typing more of a string makes it a worse match

### ISSUE THREAD

**Issue by jbellis** [atuinsh/atuin#2348]
### What did you expect to happen?

![image](https://github.com/user-attachments/assets/85cf41cb-5147-4b92-9849-a9b9857b2c0d)
Expectation is that continuing to type CASSANDRA will remain on the same match

### What happened?

![image](https://github.com/user-attachments/assets/1a133ff2-6da7-458b-8194-ff6918abce11)

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-08-06 15:05:30.040922356 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "20.04",
    "disks": [
      {
        "name": "/dev/nvme0n1p3",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/sdb1",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sda2",
        "filesystem": "ext4"
      }
    ]
  }
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
