### ISSUE TITLE
[Bug]: Atuin fzf search to behave the same like my zsh fzf search

### ISSUE THREAD

**Issue by nicolas-g** [atuinsh/atuin#2351]
### What did you expect to happen?

I would like the atuin fzf search to behave like my history fzf search when I'm not using atuin

### What happened?

atuin search results are not very accurate when compared to my zsh fzf search 

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-08-06 21:22:46.198875 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "14.5",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thernstig** [comment]
@nicolas-g I wanted to try atuin, but I really want to use fzf (and fish). Reading this bug report it seems that fzf searching the atuin history is buggy, but how exactly?

**Comment by nicolas-g** [comment]
@thernstig I just had much better results using fzf to search so I end up stop using atuin.

You can give it a try and quickly switch back if it doesn't work for you, try it your self your experience might be different.

**Comment by thernstig** [comment]
@nicolas-g You found now way to use atuin for its syncing features, but use fzf for fuzzy searching the atuin history then?

**Comment by nicolas-g** [comment]
> @nicolas-g You found now way to use atuin for its syncing features, but use fzf for fuzzy searching the atuin history then?

when you use atuin you are using atuins searching feature (whatever that is), when I'm not using atuin I'm using fzf for searching my shell history.

the behavior differs.

**Comment by ahmedelgabri** [comment]
> [@nicolas-g](https://github.com/nicolas-g) You found now way to use atuin for its syncing features, but use fzf for fuzzy searching the atuin history then?

@thernstig I think you can do this by disabling `CTRL+R` and/or `Arrow-Up` (https://docs.atuin.sh/configuration/key-binding/#disable-up-arrow) like so (change the shell to the one you are using) I'm currently trying this myself because I prefer the results I get from fzf.

```zsh
eval "$(atuin init zsh --disable-up-arrow --disable-ctrl-r)"
```

**Comment by thernstig** [comment]
> [@thernstig](https://github.com/thernstig) I think you can do this by disabling `CTRL+R` and/or `Arrow-Up` (https://docs.atuin.sh/configuration/key-binding/#disable-up-arrow) like so (change the shell to the one you are using) I'm currently trying this myself because I prefer the results I get from fzf.
> 
> eval "$(atuin init zsh --disable-up-arrow --disable-ctrl-r)"

Any good news?

**Comment by iloveitaly** [comment]
> [](https://github.com/thernstig) I just had much better results using fzf to search so I end up stop using atuin.

@nicolas-g do you have the snippet you use to integrate fzf with atuin for ctrl+r?

**Comment by nicolas-g** [comment]
> > I just had much better results using fzf to search so I end up stop using atuin.
> 
> [@nicolas-g](https://github.com/nicolas-g) do you have the snippet you use to integrate fzf with atuin for ctrl+r?

@iloveitaly I didn't integrate fzf with atuin. I had fzf and was happy, then I installed atuin and was not happy. I stopped using atuin so I can use fzf.

**Comment by iloveitaly** [comment]
😆 hahaha loved that explanation!! Great to have some humor on GitHub.

**Comment by ellie** [comment]
just an update for you all! 

with the release of `18.13.2`, we now ship a new search mode. This is _much_ more like the search you'd get with `fzf`, as it uses [nucleo](https://github.com/helix-editor/nucleo) behind the scenes. It requires that you use the Atuin Daemon - it keeps a search index warm and in-memory, so that it doesn't require building from scratch every time + should be very fast. We also have a bunch of frecency scoring changes, that should feel much better.

To enable, you have two options

1. Run `atuin setup`, say yes to the daemon. Good to go.
2. Edit your `config.toml`, with the following changes
```toml
search_mode = "daemon-fuzzy"

[daemon]
enabled = true
autostart = true
```
