### ISSUE TITLE
[Bug]: atuin status with Error: unexpected trailing characters; the end of input was expected

### ISSUE THREAD

**Issue by davidshanghai** [atuinsh/atuin#2352]
### What did you expect to happen?

atuin status
Error: unexpected trailing characters; the end of input was expected

Caused by:
    unexpected trailing characters; the end of input was expected

Location:
    crates/atuin-client/src/settings.rs:513:27

### What happened?

atuin status
Error: unexpected trailing characters; the end of input was expected

Caused by:
    unexpected trailing characters; the end of input was expected

Location:
    crates/atuin-client/src/settings.rs:513:27

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "no last sync"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "14.6",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
