### ISSUE TITLE
[Bug]: atuin + starship + zsh + accept-line override is clearing previous command?

### ISSUE THREAD

**Issue by nk9** [atuinsh/atuin#2353]
### What did you expect to happen?

I have overridden `zle`'s `accept-line` command to reset the prompt. My goal is to have the time in the _current_ prompt [reset on <kbd>Return</kbd> to be the time that the command was _executed_](https://stackoverflow.com/a/35051172/1749551). Then the command finishes, and the new prompt shows the time the previous command _ended_, until it gets reset upon submitting the next command. Here's what I've added to my `.zshrc`:

```zsh
function _reset-prompt-and-accept-line {
  zle reset-prompt
  zle .accept-line   # Note the . meaning the built-in accept-line
}
zle -N accept-line _reset-prompt-and-accept-line
```

This works correctly when I use <kbd>Return</kbd> to enter a new command. It also works if I turn off `atuin` and just use the up arrow to navigate the command history. Or if I use `atuin` to find a previous command, recall it with <kbd>Tab</kbd>, and then exectue it with <kbd>Return</kbd>.

### What happened?

When I instead use `atuin` to recall a previous command _and execute it_ using <kbd>Return</kbd> directly from the list, this `accept-line` override is causing the output of the previous command to be entirely cleared. The prompt does get reset (and the time is updated), then the output of the current command is shown, and then the next prompt is shown. But it's kind of a dealbreaker that the previous command's output disappears.

This doesn't happen if I disable the `accept-line` override, so that's clearly the problem. Of course, it also works fine if I turn off `atuin`. Am I missing a `zle` command here to make this rather unique use case work successfully with `atuin`?

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-08-07 19:20:59.086858 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "14.5",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Purple",
        "filesystem": "hfs"
      },
      {
        "name": "AV 3",
        "filesystem": "hfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
