### ISSUE TITLE
[Bug]: some commands are missed by atuin for no apparent reason?

### ISSUE THREAD

**Issue by aborrero** [atuinsh/atuin#2361]
### What did you expect to happen?

When I type on one terminal window this:

```
arturo@nostromo:~$ stty raw -echo
```

I open another terminal window, run atuin (CTRL+R) and I see the above command as the last command.

### What happened?

I typed on one terminal window this:

```
arturo@nostromo:~$ stty raw -echo
```

Then opened another terminal window, hit CTRL+R to open the atuin panel, and the above command was not present.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": false,
      "auto_sync": true,
      "last_sync": "2024-08-12 16:46:07.182128342 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Debian GNU/Linux",
    "arch": "x86_64",
    "version": "unknown",
    "disks": [
      {
        "name": "/dev/mapper/nostromo--vg-root",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext2"
      },
      {
        "name": "/dev/mapper/nostromo--vg-tmp",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/mapper/nostromo--vg-var",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/mapper/nostromo--vg-home",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
