### ISSUE TITLE
[Bug]: Fish shell plugin not loaded on startup

### ISSUE THREAD

**Issue by Stef16Robbe** [atuinsh/atuin#2364]
### What did you expect to happen?

Like the docs mention, I added `atuin init fish | source` to my `$HOME/.config/fish/config.fish`.

I expected atuin to work fully whenever I open a fish session.

### What happened?

My `CTRL` + `R` history binding does not work. It uses the default fish history. Up arrow does use atuin.

My `config.fish`:

```fish
if status is-interactive
    fish_config theme choose coolbeans
    atuin init fish | source
end
```

If I run `atuin init fish | source` manually, the CTRL R keybinding does work as expected.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "14.6.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
