### ISSUE TITLE
[Bug]: Atuin seems to randomly "forget" lots of history also strange fuzzy search behavior.

### ISSUE THREAD

**Issue by NeckBeardPrince** [atuinsh/atuin#2375]
### What did you expect to happen?

I went to search my history for `gcloud` but there were no valid hits. I know I just used that command about 20 times this week, so it didn't make sense that nothing was showing up. Well, when I say nothing, I mean nothing that has the word `gcloud` in it. None of those commands have the word gcloud, I tried "gcloud" and just `gcloud`. Nothing.

![CleanShot 2024-08-28 at 14 51 46](https://github.com/user-attachments/assets/a5f18f3a-f0a2-4b5d-9ec6-16831ce377c2)

```console
❯ docker run \
    -e KEYCLOAK_URL="<removed>" \
    -e KEYCLOAK_USER="<removed>" \
    -e KEYCLOAK_PASSWORD="<removed>" \
    -e KEYCLOAK_AVAILABILITYCHECK_ENABLED=true \
    -e KEYCLOAK_AVAILABILITYCHECK_TIMEOUT=120s \
    -e IMPORT_FILES_LOCATIONS='/config/*' \
    -v $PWD/config:/config \
    adorsys/keycloak-config-cli:latest
```

### What happened?

Running `atuin stats` atuin is counting the times I've used `gcloud`.
![CleanShot 2024-08-28 at 14 55 38](https://github.com/user-attachments/assets/cad1a5b7-1602-4b4c-8a38-c8a22d666b32)

```console
❯ atuin sync
Uploading 8 records to 0190c3daa0ed7c53933dd5eaeb013b8f/history
  [00:00:00] [####################################################################################################################################################################################################################] 8/8 (0.0s)9/0 up/down to record store
Sync complete! 37598 items in history database, force: false
❯ atuin sync --force
Uploading 1 records to 0190c3daa0ed7c53933dd5eaeb013b8f/history
  [00:00:00] [####################################################################################################################################################################################################################] 1/1 (0.0s)2/0 up/down to record store
Sync complete! 37599 items in history database, force: true
```

Checking the SQLite db 37599 is the number of rows I have.

![CleanShot 2024-08-28 at 14 58 14](https://github.com/user-attachments/assets/9a4621ae-b736-47c3-a87d-d79a2b0fd9e7)

If I search the command column for `contains gcloud` I get 675 rows.

![CleanShot 2024-08-28 at 14 59 25](https://github.com/user-attachments/assets/7608e05f-7c28-4db1-9abc-913e1613c89f)

If I `cat ~/.zsh_history | grep gcloud` I see results.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-08-28 19:16:08.379861 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "14.6.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Backups",
        "filesystem": "apfs"
      },
      {
        "name": "Time Machine",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
