### ISSUE TITLE
[Bug]: Glitch after a "base64 --decode" command

### ISSUE THREAD

**Issue by edpichler** [atuinsh/atuin#2376]
### What did you expect to happen?

I typed a command ending with `| base64 --decode`

### What happened?

![image](https://github.com/user-attachments/assets/985ced40-02c3-44ee-93b2-ed0c012833ae)

Strange I could not reproduce it anymore. It was not the first time it happened, though.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": false,
      "auto_sync": true,
      "last_sync": "2024-08-29 12:58:48.134778 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "14.6.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
