### ISSUE TITLE
[Bug]: History not synced between old machine and new

### ISSUE THREAD

**Issue by phinze** [atuinsh/atuin#2379]
### What did you expect to happen?

First of all - love this project! 😄 🫶 

I'm in the process of rebuilding my NixOS-based development VM. Because the new VM is using NixOS 24.05, it has atuin 18.2.0, while old machine was on NixOS 23.11 with atuin 18.0.1.

I ran `atuin login` and `atuin sync` and expected my full ~28k history to be available on the new machine.

### What happened?

Instead, it logged in and synced successfully, but only was able to see its own history.

Old machine `atuin stats`:

```
Total commands:   97
Unique commands:  44
```

New machine:

```
Total commands:   27800
Unique commands:  14167
```

### Atuin doctor output

(From new machine, old machine does not have the command, but I'm happy to provide any details on request!)

```yaml
atuin:
  version: 18.2.0
  sync:
    cloud: true
    records: true
    auto_sync: true
    last_sync: 2024-09-03 0:14:46.208984135 +00:00:00
shell:
  name: fish
  default: unknown
  plugins:
  - atuin
system:
  os: NixOS
  arch: x86_64
  version: '24.05'
  disks:
  - name: /dev/disk/by-label/nixos
    filesystem: ext4
  - name: /dev/disk/by-label/nixos
    filesystem: ext4
  - name: /dev/vda1
    filesystem: vfat
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
