### ISSUE TITLE
[Bug]: ctrl-n doesn't exit scroll on last line

### ISSUE THREAD

**Issue by multivac61** [atuinsh/atuin#2381]
### What did you expect to happen?

Similar to how the arrow keys work, e.g., pressing the down key, pressing `ctrl-n` should exit scroll when scrolling past the first item

### What happened?

![CleanShot 2024-09-06 at 11 41 50](https://github.com/user-attachments/assets/2303551d-128d-4aac-b59e-8059daaf3596)

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": false,
      "auto_sync": true,
      "last_sync": "2024-08-08 16:44:30.734981 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "14.6.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

 ~/.config/atuin/config.toml

```
enter_accept = true
exit_mode = "return-query"
keymap_mode = "auto"
prefers_reduced_motion = true
sync_frequency = "0"
update_check = false
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
