### ISSUE TITLE
[Bug]: ctrl+r doesn't work in zsh with sshx.io

### ISSUE THREAD

**Issue by luochen1990** [atuinsh/atuin#2385]
### What did you expect to happen?

`ctrl+r` trigger the reverse search correctly.

### What happened?

> Error: The cursor position could not be read within a normal duration

![image](https://github.com/user-attachments/assets/f4063a18-c98d-45d2-8364-990d1d20cdcd)

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-09-13 7:46:05.089123063 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "NixOS",
    "arch": "x86_64",
    "version": "24.11",
    "disks": [
      {
        "name": "/dev/dm-0",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/dm-0",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme1n1p4",
        "filesystem": "fuseblk"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/dm-0",
        "filesystem": "btrfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
