### ISSUE TITLE
Consider publishing on WinGet

### ISSUE THREAD

**Issue by Lemonzyy** [atuinsh/atuin#2386]
On Windows, running `curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh` doesn't work so I have to build from source. However, for Windows users who don't want to install Rust on their computer Winget would be a great installation method (which is used by other tools such as helix, zoxide, bat, kondo, ...).

**Comment by zippozeng** [comment]
There is new news on this issue？please help support Windows

**Comment by djmattyg007** [comment]
Given the recent introduction of Powershell support, it would be amazing to see this coupled with publishing to WinGet :pray:

**Comment by ltrzesniewski** [comment]
(this is related to #2966)

**Comment by mloskot** [comment]
I have just submitted PR with the Atuin package 
- https://github.com/microsoft/winget-pkgs/pull/331328

Now I'm waiting for the review of the winget-pkg maintainers (I have some history of successful package submissions).

Perhaps @ellie and other maintainers of Atuin could also have a look at the manifest that PR and verify it for any mistakes, especially w.r.t. to names I used for package identifier, publisher, copyright, etc.

Next, once submitted, keeping the winget package up to date using the awesome https://github.com/russellbanks/Komac tool is a trivial task, and can also be automated with GHA.

**Comment by ltrzesniewski** [comment]
Heh, I was just reading the winget documentation when you sent this message 😅 Nice!

I have a few questions:
- Which `PackageIdentifier` is better: `Atuinsh.Atuin` or `Atuin.Atuin`?
- Which `PublisherUrl`/`PackageUrl` is better? ``https://atuin.sh`` or ``https://github.com/atuinsh``?
- Where will `atuin.exe` end up? I suppose it won't be in the same directory as what [`atuin-installer.ps1`](https://github.com/atuinsh/atuin/releases/download/v18.11.0/atuin-installer.ps1) generates? (`~/.atuin/bin`)
- I suppose the exe will end up in the PATH? (stupid question, but you never know)
- Should `bash`/`fish` etc be in the tags?

Thanks for doing this! 🙂

**Comment by mloskot** [comment]
@ltrzesniewski  I'll try to answer your questions:

> Which `PackageIdentifier` is better: `Atuinsh.Atuin` or `Atuin.Atuin`?

I had that question in mind too, but decided to keep the identifier aligned with the GitHub URL of the project, thinking, if a new tool appears in the github.com/Atuinsh space in future, then it can get clear identifier like `Atuinsh.NewCoolTool`, whereas `Atuin.NewCoolTool` could be confusing as "is this Atuin add-in?", etc.

However, if Atuin developers decide to change it, at any point, then there is no problem to submit a correcting PR to winget-pkgs.

> Which `PublisherUrl/PackageUrl` is better? `https://atuin.sh` or `https://github.com/atuinsh`?

Good point. I've just corrected the `PublisherUrl` in the package PR.

> Where will `atuin.exe` end up?

In WinGet's special place :) See also below.

<img width="1026" height="198" alt="Image" src="https://github.com/user-attachments/assets/efd1bf74-602c-4b1d-9ae1-67434f41a10a" />

<img width="827" height="139" alt="Image" src="https://github.com/user-attachments/assets/7eb7fdc1-7f13-45e2-9c53-18a973025dd6" />

> I suppose the exe will end up in the PATH? (stupid question, but you never know)

Yes, it will, aliased. WinGet adds so called "portable command alias" to special locations which are in `PATH`, gist from `winget --info`:

<img width="767" height="103" alt="Image" src="https://github.com/user-attachments/assets/41322bec-3249-4511-a136-67511e4c99a8" />

Adding of an alias is indicated with this yellow line in the `winget install` output:

<img width="346" height="58" alt="Image" src="https://github.com/user-attachments/assets/bff2d916-05d4-429e-b2fc-a60a42738455" />

> Should bash/fish etc be in the tags?

Good catch. Removed. Added `powershell`.

**Comment by ltrzesniewski** [comment]
Thanks! 👍

I'll wait until the package is released, and send a PR which adds the necessary info to the docs *"Manual installation"* section.

I think `winget` is the better way to proceed than `atuin-installer.ps1`.

**Comment by mloskot** [comment]
Pleasure! 💯 

It is worth to mention that the WinGet manifest that I submitted does not perform any user-specific configuration. It just deploys the program. Then, it's up to users to set their environment up, for example, by running this PowerShell one-liner or similar:

```powershell
Write-Output "atuin init powershell | Out-String | Invoke-Expression" >> $PROFILE
```

> I think `winget` is the better way to proceed than `atuin-installer.ps1`.

Possibly, yes.

WinGet is a Windows-native solution and users can upgrade software, including Atuin, with single `winget upgrade -all` without performing a single click, which is nice :)

**Comment by ltrzesniewski** [comment]
Yes, I was going to write exactly that: a `winget` tab in *Installing the binary* and a `PowerShell` tab in *Installing the shell plugin*. 🙂

**Comment by mcexit** [comment]
I routinely create WinGet manifests. The one submitted looks mostly good, but I did make my own prior & wanted to share it should you find any differences useful.

> Note: I believe manifest version 1.12.0 has already been finalized:

`Atuin.AtuinCLI.installer.yaml`
```
# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

Installers:
  - Architecture: x64
    InstallerSha256: 29DDB786F3E18964D3BE7503D38293E60704E7E36E9A23B360311EE5FC092B1A
    InstallerUrl: https://github.com/atuinsh/atuin/releases/download/v18.11.0/atuin-x86_64-pc-windows-msvc.zip
InstallerType: zip
ManifestType: installer
ManifestVersion: 1.12.0
NestedInstallerFiles:
  - PortableCommandAlias: atuin
    RelativeFilePath: atuin.exe
NestedInstallerType: portable
PackageIdentifier: Atuin.AtuinCLI
PackageVersion: 18.11.0
ReleaseDate: 2026-01-12
```

`Atuin.AtuinCLI.locale.en-US.yaml`
```
# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

Copyright: Copyright (C) 2021 Ellie Huxtable
CopyrightUrl: https://github.com/atuinsh/atuin/blob/main/LICENSE
Documentations:
  - DocumentLabel: Getting Started
    DocumentUrl: https://docs.atuin.sh/cli/guide/getting-started/
  - DocumentLabel: Setting up Sync
    DocumentUrl: https://docs.atuin.sh/cli/guide/sync/
  - DocumentLabel: Config
    DocumentUrl: https://docs.atuin.sh/cli/configuration/config/
  - DocumentLabel: FAQ
    DocumentUrl: https://docs.atuin.sh/cli/faq/
License: MIT License
LicenseUrl: https://github.com/atuinsh/atuin/blob/main/LICENSE
ManifestType: defaultLocale
ManifestVersion: 1.12.0
Moniker: Atuin CLI
PackageIdentifier: Atuin.AtuinCLI
PackageLocale: en-US
PackageName: Atuin CLI
PackageUrl: https://atuin.sh/#cli-section
PackageVersion: 18.11.0
Publisher: Atuin
PublisherSupportUrl: https://github.com/atuinsh/atuin/issues
PublisherUrl: https://atuin.sh
ReleaseNotesUrl: https://github.com/atuinsh/atuin/releases
ShortDescription: Sync, search, & backup your shell history with end-to-end encryption
Tags:
  - dotfiles
  - encryption
  - history
  - open-source
  - powershell
  - rust
  - search
  - shell
  - sqlite
  - stats
  - sync
  - terminal
```

`Atuin.AtuinCLI.yaml`
```
# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json

DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.12.0
PackageIdentifier: Atuin.AtuinCLI
PackageVersion: 18.11.0
```
