### ISSUE TITLE
[Bug]: integer underflow when result list empty and pressing "up"

### ISSUE THREAD

**Issue by cloneable** [atuinsh/atuin#2393]
### What did you expect to happen?

No action.

### What happened?

```
thread 'main' panicked at crates/atuin/src/command/client/search/interactive.rs:537:41:
attempt to subtract with overflow
```

https://github.com/atuinsh/atuin/blob/6e15286f0c94b89d4c5f9b8fa1e9a72cd209017c/crates/atuin/src/command/client/search/interactive.rs#L537

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0-beta.3",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.0",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
