### ISSUE TITLE
[Bug]: Control-A Not Moving to Beginning of Line

### ISSUE THREAD

**Issue by iloveitaly** [atuinsh/atuin#2397]
### What did you expect to happen?

Move to the cursor to the beginning of the line.

![iTerm2 - tmux standard (tmux) 2024-09-26 at 11 17 13 AM](https://github.com/user-attachments/assets/fcdcaa26-ae00-4450-acaa-84d3aa2af9c1)

### What happened?

Nothing

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "14.6.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
