### ISSUE TITLE
[Bug]: atuin does not sync correctly

### ISSUE THREAD

**Issue by jankatins** [atuinsh/atuin#2406]
### What did you expect to happen?

I wanted to setup a new laptop and expected that after `atuin login`, all old shell history from other computeres were available. It was not. Also, when I checked on other computers, they did not have the same amount of history, even after `atuin sync`. 

### What happened?

This is the session of an *old* computer running for days. As far as I can see, it shows that it didn't download history which was uploaded by another computer. I had to run ` atuin sync -f` to get it to download additional history entries. I then ran it as well on a new computer (with ~40 entries) and it also started downloading entries there. Still, the new computer now shows 20425 entries (after about five `atuin sync -f` runs over 20min, similar increasing items like the below session), the old computer shows now 20728 (see latest run below):

```shell
[18:39:03] λ  atuin status
Atuin v18.3.0 - Build rev 9be49e434e549d6b13928b530139b66fef6171f1

[Local]
Sync frequency: 10m
Last sync: 2024-10-03 16:38:58.260977479 +00:00:00
History count: 10041
Deleted history count: 0

[Remote]
Address: https://api.atuin.sh
Username: jankatins

~
[18:39:09] λ  atuin sync
Sync complete! 10042 items in history database, force: false

~
[18:39:26] λ  atuin sync -f
Sync complete! 17615 items in history database, force: true

~ took 5s
[18:40:56] λ  atuin sync -f
Sync complete! 17926 items in history database, force: true

~ took 48s
[18:41:49] λ  atuin sync -f
Sync complete! 19328 items in history database, force: true

[18:45:52] λ  atuin sync -f
Sync complete! 20728 items in history database, force: true
```

I then checked for the history of the computer I decommissioned a few days ago and the latest data I have from that laptop is from "1mo ago" (I just checked for a command which run almost daily, no idea if there is a better way to search for by hostname?). So apparently, atuin did NOT sync for about a month? Thankfully I didn't do a lot of new stuff during the last month, so that's not the end of the world, but it is still scary that sync doesn't work correctly. :-(

### Atuin doctor output

```yaml
# Old computer
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": false,
      "auto_sync": true,
      "last_sync": "2024-10-03 16:42:01.426665248 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Debian GNU/Linux",
    "arch": "x86_64",
    "version": "unknown",
    "disks": [
      {
        "name": "/dev/mapper/bloodaxe--vg-root",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext2"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
