### ISSUE TITLE
[Bug]: Seeing Error: migration 20231127090831... after every prompt

### ISSUE THREAD

**Issue by slochower** [atuinsh/atuin#2415]
### What did you expect to happen?

No `atuin` output.

### What happened?

After updating to 18.x from 17.x, I now see

```
Error: migration 20231127090831 was previously applied but is missing in the resolved migrations
```

after every command. I came across this post https://forum.atuin.sh/t/migration-was-previously-applied-but-is-missing-in-the-resolved-migrations/84 but it says **do not** delete for post 17.2. Is there a recommended action for 18.3.0?

### Atuin doctor output

```yaml
❯ atuin doctor
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "x86_64",
    "version": "14.6.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "OWC",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
