### ISSUE TITLE
[Bug]: Atuin displays entries with a date in the future

### ISSUE THREAD

**Issue by Ember-ruby** [atuinsh/atuin#2417]
### What did you expect to happen?

Atuin should not consider a command ran in the future to be the last command run

### What happened?

atuin sorts these entries in front of everything, pinning them to the top of the history until the date passes

![Screenshot_13_1539441](https://github.com/user-attachments/assets/b72c952b-5852-4f6f-b605-0f745c501a79)
![Screenshot_13_1533421](https://github.com/user-attachments/assets/b7702779-86e5-4fd9-8f23-92513fd9a0d4)
(as of now the date is `Sun 13 Oct 2024 15:43 AEDT`)

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-10-13 4:39:09.42551255 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "NixOS",
    "arch": "x86_64",
    "version": "24.11",
    "disks": [
      {
        "name": "/dev/nvme1n1p2",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme1n1p2",
        "filesystem": "btrfs"
      },
      {
        "name": "systemd-1",
        "filesystem": "autofs"
      },
      {
        "name": "systemd-1",
        "filesystem": "autofs"
      },
      {
        "name": "/dev/nvme1n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/nvme0n1",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdb1",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/md127",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme1n1p2",
        "filesystem": "btrfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
