### ISSUE TITLE
[Bug]: Getting 404 on sync with self-hosted on kubernetes

### ISSUE THREAD

**Issue by marnas** [atuinsh/atuin#2421]
### What did you expect to happen?

I followed the docs for deploying atuin on a kubernetes cluster and I am able to register a new user and login, however I'm facing the following error when I try to sync

### What happened?

❯ atuin status
Atuin v18.3.0 - Build rev NO_GIT

[Local]
Sync frequency: 10m
Last sync: 1970-01-01 0:00:00.0 +00:00:00
[Remote]
Address: https://atuin.marnas.sh
Username: marnas

❯ atuin sync
Error: a request to the sync server failed: "There was an error with the atuin sync service: Status 404.\nIf the problem persists, contact the host"

Location:
    crates/atuin/src/command/client/sync.rs:91:38

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "1970-01-01 0:00:00.0 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "NixOS",
    "arch": "x86_64",
    "version": "24.11",
    "disks": [
      {
        "name": "/dev/disk/by-uuid/e105daca-11af-4c6f-a56c-b04df968ac88",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/disk/by-uuid/e105daca-11af-4c6f-a56c-b04df968ac88",
        "filesystem": "ext4"
      },
      {
        "name": "systemd-1",
        "filesystem": "autofs"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ellie** [comment]
The docs don't actually detail how you should setup an ingress - that part is up to you. Would you be able to share your ingress config please?

**Comment by marnas** [comment]
Yes of course, I use traefik as ingress controller and here's my config for atuin
``` 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atuin
  namespace: atuin
spec:
  tls:
  - hosts:
      - atuin.marnas.sh
    secretName: atuin-lets-encrypt
  rules:
  - host: atuin.marnas.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: atuin
            port:
              number: 8888
```
Am I missing something?

**Comment by marnas** [comment]
After some digging I found out there was a misconfiguration on my side and there's no issue with atuin.

For anybody facing a similar problem, in my case there was an ingressRoute with ```matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)``` that got deployed with traefik when I enabled the dashboard in the helm chart. 

I'm not sure how that was interfering with an ingress deployed in a different namespace and under a different subdomain, but the issue disappeared the moment I removed the ingressRoute.

**Comment by jswolvaardt** [comment]
Sorry to revive this one, but I have a similar issue, except it is a clean cluster with no other ingress configured, yet.

Ingress for Atuin - values in angular brackets have been redacted

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atuin
  namespace: atuin
  annotations:
    cert-manager.io/cluster-issuer: <domain>-issuer
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  tls:
  - hosts:
      - atuin.<domain>
      - atuin.<sub>.<domain>
    secretName: atuin-cert
  rules:
  - host: atuin.<sub>.<domain>
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: atuin
            port:
              number: 8888
```

I am using Cilium ingress and cert-manager for the ACME cert.
I have tested by sidestepping the Ingress and rather using the NodePort, and was able to successfully register and sync my history. Only when I switched it back to use the ingress url, did I receive the 404 again.
Opening the url in a browser works correctly.
