### ISSUE TITLE
[Bug]: Error thrown with last nushell version

### ISSUE THREAD

**Issue by justbispo** [atuinsh/atuin#2423]
### What did you expect to happen?

The shell plugin shouldn't throw any error, starship's prompt symbol shouldn't be detecting the error on the shell plugin.

### What happened?

This is kind of a weird report. Since last nushell version (0.99.0) the [shell plugin file](https://github.com/atuinsh/atuin/blob/main/crates/atuin/src/shell/atuin.nu) throws an error when it's sourced.
There's no actual text of the error and, from my short test, it seems the program is working normally. I've only noticed the error because of the starship's prompt symbol going red, which indicates a program exited with an error.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-10-16 22:58:13.665603487 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "nu",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Arch Linux",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
      {
        "name": "/dev/sda6",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sda6",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sda3",
        "filesystem": "fuseblk"
      },
      {
        "name": "/dev/sda3",
        "filesystem": "fuseblk"
      },
      {
        "name": "/dev/sda2",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/sdb1",
        "filesystem": "btrfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
