### ISSUE TITLE
[Bug]: Config file recognized but not being read

### ISSUE THREAD

**Issue by gibtree** [atuinsh/atuin#2429]
### What did you expect to happen?

Editing the config file noted in `atuin info` should result in changed behavior. This is client-only and installed via `cargo`, no server is configured (AFAIK).

### What happened?

Hi, I've been trying to get `filter_mode_shell_up_key_binding` working for a while now. I decided to try and set just the `filter_mode` as well, and that's not working either. According to `atuin info`, I'm editing the correct config. I tried with `ATUIN_CONFIG_DIR` unset and manually set to the config dir, neither seems to change the behavior.

### Atuin doctor output

```yaml
Config files:
client config: "/home/me/.config/atuin/config.toml"
server config: "/home/me/.config/atuin/server.toml"
client db path: "/home/me/.local/share/atuin/history.db"
key path: "/home/me/.local/share/atuin/key"
session path: "/home/me/.local/share/atuin/session"

Env Vars:
ATUIN_CONFIG_DIR = "/home/me/.config/atuin"

Version info:
version: 18.3.0

Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "24.04",
    "disks": [
      {
        "name": "/dev/nvme0n1p5",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p5",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/nvme1n1p1",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
