### ISSUE TITLE
[Bug]: Error: pool timed out....

### ISSUE THREAD

**Issue by Graninius** [atuinsh/atuin#2435]
### What did you expect to happen?

Working without this error )

### What happened?

Every time when I open the terminal I get this error: 
```
Error: pool timed out while waiting for an open connection
Location:
    /usr/src/debug/atuin/atuin-18.3.0/crates/atuin-client/src/record/sqlite_store.rs:48:20
Error: pool timed out while waiting for an open connection
Location:
    /usr/src/debug/atuin/atuin-18.3.0/crates/atuin-client/src/record/sqlite_store.rs:48:20
```
and have to wait for about 10-15sec before it's ready to work.

### Atuin doctor output

```yaml
atuin doctor
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Manjaro Linux",
    "arch": "x86_64",
    "version": "24.1.1",
    "disks": [
      {
        "name": "/dev/sdb1",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sda1",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
