### ISSUE TITLE
[Bug]: account login and registration failure

### ISSUE THREAD

**Issue by SansGuidon** [atuinsh/atuin#2436]
### What did you expect to happen?

Account registration and login fails

This afternoon I did create an account and later during the day I've tried logging in and syncing another machine with this account, without success.
I've attempted to change the password, but that was not enough.
As a result, I've deleted my account (because no way to reset password).
Since then I'm attempting a new account registration, which fails all the time.
I've attempted the operation on a Linux Ubuntu 24.04 and on MacOs, in both cases I couldn't register an account.

### What happened?

ads  atuin register
Registering for an Atuin Sync account
Please enter username: anythingwithwords
Please enter email: anythingwithwordsg@duck.com
Please enter password:
Error: Invalid request to the service: 400 Bad Request - failed to add user.

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [],
    "preexec": null
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "13.4",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
