### ISSUE TITLE
[Bug]: Error: Permission denied (os error 13)

### ISSUE THREAD

**Issue by HwapX** [atuinsh/atuin#2438]
### What did you expect to happen?

The search panel open.

### What happened?

Recently i started getting this error when running on **zsh**.

The following error happens when i try run it.
```
Error: Permission denied (os error 13)

Location:
    crates/atuin/src/command/client/search/interactive.rs:990:18
```

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "24.04",
    "disks": [
      {
        "name": "/dev/sdc2",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc2",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc2",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/sda1",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sda1",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdb1",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdb2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdb1",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdb3",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
