### ISSUE TITLE
[Bug]: Binary does not run on raspbian bullseye, requires newer glibc

### ISSUE THREAD

**Issue by barrelltitor** [atuinsh/atuin#2439]
### What did you expect to happen?

I expected to be able to use atuin after using hte installation script

### What happened?

I was unable to use atuin as the binary is incompatible with the glibc version on raspbian, getting the following:

```
atuin
atuin: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by atuin)
atuin: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by atuin)
atuin: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by atuin)
[ble: exit 1]
```

```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/

ldd --version
ldd (Debian GLIBC 2.31-13+rpt2+rpi1+deb11u10) 2.31

```
On an x86 debian with the exact same os release, this works and doesn't require glibc 2.34+
```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


ldd --version
ldd (Debian GLIBC 2.31-13+deb11u11) 2.31
```

### Atuin doctor output

```yaml
Atuin can't run at all, same output of course

atuin doctor
atuin: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by atuin)
atuin: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by atuin)
atuin: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by atuin)
[ble: exit 1]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
