### ISSUE TITLE
[Bug]: different history depending on which terminal is used

### ISSUE THREAD

**Issue by beeb** [atuinsh/atuin#2440]
### What did you expect to happen?

When I do ctrl-r inside of any terminal, I should see the full history of my account.

### What happened?

I'm using both Alacritty and the built-in terminal of VSCode in parallel.
Since a few days ago, when I do "ctrl-r" inside Alacritty, I see my full history for the "GLOBAL" filter (I see 89k for the count in the top-right).
However, if I do "ctrl-r" inside the VSCode built-in terminal (it's also "GLOBAL" in the filter on the bottom), I see only 75 for the history count.

I had to cleanup my local database the other day (with the `store purge` command) because it got messed up due to me logging in and out and providing the wrong encryption key once. In the end I managed to get back to a proper state but only if I use the Alacritty terminal.

Note that I'm on Ubuntu 24.04.

Notice that in the output below, the `last_sync` date is messed up when I run `doctor` inside of VSCode. However, if I run `doctor` inside of Alacritty, then I see `"last_sync": "2024-07-01 15:36:26.944704805 +00:00:00"`. All the other fields are the same between both terminals.

When I do `atuin key` I get different results depending on which terminal I use, which does not make a lot of sense.

When I do `atuin status` from VSCode, I get:

```
❯ atuin status
Atuin v18.3.0 - Build rev NO_GIT

[Local]
Sync frequency: 0
Last sync: 1970-01-01 0:00:00.0 +00:00:00
[Remote]
Address: https://my-selfhosted-instance.com
Username: beeb
```

However, from Alacritty I get:

```
❯ atuin status
Atuin v18.3.0 - Build rev NO_GIT

[Local]
Sync frequency: 0
Last sync: 2024-07-01 15:36:26.944704805 +00:00:00
[Remote]
Address: https://my-selfhosted-instance.com
Username: beeb
```

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "1970-01-01 0:00:00.0 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "24.04",
    "disks": [
      {
        "name": "/dev/mapper/ubuntu--vg-ubuntu--lv",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/mapper/ubuntu--vg-ubuntu--lv",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
