### ISSUE TITLE
[Bug]: I can´t login in my account from another machine

### ISSUE THREAD

**Issue by edpichler** [atuinsh/atuin#2449]
### What did you expect to happen?

I expect to log in on atuin when I am on another machine. I expect to use the same account in macOS and Ubuntu.

### What happened?

I have an account in MacOS that I can´t log in to when I use my Ubuntu. 
Maybe some incompatibility in decryption? 

I double-checked my encryption key but:

```
Re-encrypting local store with new key
Error: attempting to decrypt with incorrect key. currently using k4.lid.6DDw3x_1FlN4M1c0rVML3OUIQbP2bdb3M38pShCTxZmb, expecting k4.lid.hO305G0THWaipv08AyscYRiJJ6n3zyKA4XzU4o-aOVFe

```

### Atuin doctor output

```yaml
atuin doctor
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "22.04",
    "disks": [
      {
      {
        "name": "/dev/sdd",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdd",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
