### ISSUE TITLE
[Bug]: Unexpectedly getting a 404 when registering to my server

### ISSUE THREAD

**Issue by axelson** [atuinsh/atuin#2455]
### What did you expect to happen?

I expected that after setting the IP address of my server where atuin is running that I would be able to login and register from my clients.

### What happened?

```
> atuin register
Registering for an Atuin Sync account
Please enter username: jason
Please enter email: jason@myemail.com
Please enter password:
Error: There was an error with the atuin sync service: Status 404.
If the problem persists, contact the host

Location:
    /Users/runner/work/atuin/atuin/crates/atuin-client/src/api_client.rs:162:9
```

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "14.6.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
