### ISSUE TITLE
[Bug]: Atuin appears to interfere with Oh-My-Posh

### ISSUE THREAD

**Issue by Eloquencere** [atuinsh/atuin#2464]
### What did you expect to happen?

When having transient-prompt enabled in `oh-my-posh`  and triggering `Atuin` with `ctr+r` or with `up-arrow` I expect my command of choice from my history to be moved over to the prompt.

### What happened?

While the command is *actually* moved over, it isn't visible until I press `Enter` or type another command upon which, the previous command executes. This makes the whole experience quite weird to work with. I even raised this issue with the devs of `oh-my-posh`, they said the same `zsh` function that is used by the transient prompt feature of `oh-my-posh` is being overwritten by `Atuin`, while they said they'll look into it, they also said it's not a problem with `oh-my-posh` ([Issue #5781](https://github.com/JanDeDobbeleer/oh-my-posh/issues/5781#issuecomment-2496003653)).

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "24.04",
    "disks": [
      {
        "name": "/dev/sda2",
        "filesystem": "ext4"
      },
      {
        "name": "vmhgfs-fuse",
        "filesystem": "fuse.vmhgfs-fuse"
      },
      {
        "name": "vmhgfs-fuse",
        "filesystem": "fuse.vmhgfs-fuse"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
