### ISSUE TITLE
[Bug]: Failed to verify local store encryption

### ISSUE THREAD

**Issue by dougg0k** [atuinsh/atuin#2466]
### What did you expect to happen?

For it to import / sync properly on login and pass verification.

Is there anything that can be done to fix this, it has happened more than once, not sure how I would set a encryption key now, without losing more history data?!

### What happened?

Hi,

When I log-in from a new machine, there is a new type of error (that didnt happen before) that caused me to lose a good portion of history.

I never set a encryption key before, always left blank, but it gives an error, as if it were expecting one.

```
❯ atuin store verify
Verifying local store can be decrypted with the current key
Failed to verify local store encryption: attempting to decrypt with incorrect key. currently using k4.lid.PPDfcIrX.........., expecting k4.lid.gRCWEKF8s_..........

Location:
    /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/atuin-client-18.3.0/src/record/encryption.rs:132:9
```

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "1970-01-01 0:00:00.0 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "nu",
    "default": "nu",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "CachyOS Linux",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
      ...disks
    ]
  },
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
