### ISSUE TITLE
[Bug]: thread 'main' panicked at stats.rs:196:14: window size must be non-zero

### ISSUE THREAD

**Issue by will** [atuinsh/atuin#2470]
### What did you expect to happen?

A nice error message instead of a rust panic when running `atuin stats year -n0`

### What happened?

```
❯ RUST_BACKTRACE=1 atuin stats year -n0
thread 'main' panicked at crates/atuin-history/src/stats.rs:196:14:
window size must be non-zero
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: atuin_history::stats::compute
   4: atuin::command::client::Cmd::run_inner::{{closure}}
   5: tokio::runtime::scheduler::current_thread::Context::enter
   6: tokio::runtime::context::scoped::Scoped<T>::set
   7: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
   8: tokio::runtime::context::runtime::enter_runtime
   9: tokio::runtime::runtime::Runtime::block_on
  10: atuin::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.1.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
