### ISSUE TITLE
[Bug]: `Failed to verify local store encryption`, but the key is the same across all machines

### ISSUE THREAD

**Issue by MarvinJWendt** [atuinsh/atuin#2479]
### What did you expect to happen?

`atuin store verify` should complete without errors and the store should be synced correctly.

### What happened?

I noticed that my macOS host does not have history from my NixOS host, so I tried to pull the store on my macOS host, which resulted in an error.

Running `atuin store verify`:

```
Verifying local store can be decrypted with the current key
Failed to verify local store encryption: attempting to decrypt with incorrect key. currently using k4.lid.IvzIBSxCf******, expecting k4.lid.f-j2OIg-od2yAcuBARd*******

Location:
    crates/atuin-client/src/record/encryption.rs:132:9
```

Atuin nix config:

```nix
{ config, pkgs, ... }:

{

  # Put ../../keys/atuin/atuin.key into ~/.config/atuin/atuin.key
  home.file."atuin/atuin.key".source = ../../.config/atuin/atuin.key;

  programs.atuin = {
    enable = true;

    settings = {
      sync_address = "https://atuin.mjw.dev";
      key_path = "~/.config/atuin/atuin.key";
      auto_sync = true;
      sync_frequency = "1m";
      filter_mode = "global";
      enter_accept = false;
      records = true;
    };
  };
}
```

Compiled atuin config (by nix):

```toml
auto_sync = true
enter_accept = false
filter_mode = "global"
key_path = "~/.config/atuin/atuin.key"
records = true
sync_address = "https://***********"
sync_frequency = "1m"
```

The key is the same across all machines (I verified the hash of the key file across hosts) and hasn't changed in the last 6 months.

`atuin info` also seems to use the right files:

```
Config files:
client config: "/Users/******/.config/atuin/config.toml"
server config: "/Users/******/.config/atuin/server.toml"
client db path: "/Users/******/.local/share/atuin/history.db"
key path: "/Users/******/.config/atuin/atuin.key"
session path: "/Users/******/.local/share/atuin/session"

Env Vars:
ATUIN_CONFIG_DIR = "None"

Version info:
version: 18.3.0
```

`atuin store purge` and re-pull did not fix this issue.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": false,
      "records": false,
      "auto_sync": true,
      "last_sync": "2024-12-09 12:36:29.215083 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "nu",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "14.7.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
