### ISSUE TITLE
[Bug]: atuin not able to search for the command which is already present in the history

### ISSUE THREAD

**Issue by sonulohani** [atuinsh/atuin#2483]
### What did you expect to happen?

atuin Ctrl+R should able to filter out the command i am looking thats already present in the history

### What happened?

atuin is not able to list the command when searched

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-12-13 5:18:08.286210305 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Linux Mint",
    "arch": "x86_64",
    "version": "22.1",
    "disks": [
      {
        "name": "/dev/mapper/vgmint-root",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
