### ISSUE TITLE
[Bug]:  last_sync year show 1970

### ISSUE THREAD

**Issue by dougg0k** [atuinsh/atuin#2500]
### What did you expect to happen?

To show the latest date.

### What happened?

Why `atuin doctor`, show last_sync with 1970 as the year?

```
{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "1970-01-01 0:00:00.0 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "nu",
    "default": "nu",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "CachyOS Linux",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
      ...disks
    ]
  }
}
```

```
 ❯ atuin store status
host: 019374cf-... <- CURRENT HOST
        store: history
                idx: 5692
                first: 01940a40-...
                        created: 2024-12-27 22:33:20.557657957 +00:00:00
                last: 01940a40-...
                        created: 2024-12-27 22:33:20.598446091 +00:00:00
```

```
❯ atuin status
Atuin v18.4.0 - Build rev dc7c26a640b1a134528caa894b3339c443b917b4

[Local]
Sync frequency: 10m
Last sync: 1969-12-31 21:00:00.0 -03:00:00
[Remote]
Address: https://api.atuin.sh
Username: user

```

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "1970-01-01 0:00:00.0 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "nu",
    "default": "nu",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "CachyOS Linux",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
      ...disks
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
