### ISSUE TITLE
[Bug]: No commands being stored

### ISSUE THREAD

**Issue by sazzer** [atuinsh/atuin#2511]
### What did you expect to happen?

When running shell commands, the command should be stored into the history for later retrieval.****

### What happened?

The fact that a command was run is being stored, but the command itself isn't. This is making the tool pretty useless :(

When I run `atuin history list` I get output like this:
```
-> % atuin history list --format "{time} - {duration} - {command}"
2024-12-30 12:52:03 - 7ms -
2024-12-30 12:52:40 - 2s -
2024-12-30 12:54:04 - 54s -
2024-12-30 12:55:00 - 2m -
2024-12-30 12:57:28 - 90ms -
2024-12-30 12:58:02 - 16ms -
2024-12-30 12:58:06 - 17ms -
2024-12-30 12:58:14 - 18ms -
2024-12-30 12:58:23 - 23ms -
2024-12-30 12:59:25 - 0s -
```

And the timestamps correspond to when commands were run. However, as you can see there is no command stored against any of the entries.

I've also manually opened the SQLite database to have a look, and this is what's being stored:
```
-> % sqlite3 ~/.local/share/atuin/history.db
SQLite version 3.43.2 2023-10-10 13:08:14
Enter ".help" for usage hints.
sqlite> select id, timestamp, command from history;
019417ac0a6e7ca0875f296b8d87b704|1735563938414779000|
019417ac0cd57cf38c37ede81d461e91|1735563939029984000|
019417ac0eb471c29e772d1a1abb5126|1735563939508478000|
019417ad7ee27fe283c411f08f4a7229|1735564033762788000|
019417aec7b37fc3b9530aeb8ddb5923|1735564117939667000|
```

So you can see that the `command` column is just blank.

Things that I've tried to see if it made any difference - and none of them did:
* Using both zsh and bash
* Using both iTerm2 and Terminal.app
* Using the recommended installation approach, `cargo install atuin` and `brew install atuin` (Uninstalling between each of those)
* Deleting `~/.local/share/atuin` in case anything was corrupted in there

The only thing I *haven't* done is to configure sync - which I'm less interested in using, and which I don't believe is relevant to what's going on here...

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "14.7.2",
    "disks": [
      {
        "name": "Untitled",
        "filesystem": "apfs"
      },
      {
        "name": "Untitled",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
