### ISSUE TITLE
[Bug]: wrapped command: Command Evolution stats ignore common_prefix setting

### ISSUE THREAD

**Issue by TopherIsSwell** [atuinsh/atuin#2512]
### What did you expect to happen?

when running `atuin wrapped` that the Command Evolution section would not list any command in the common_prefix setting.

### What happened?

`sudo` was listed in the common_prefix setting, but it was listed in the Command Evolution stats section of `atuin wrapped`:

```
🔍 Command Evolution:
  Top Commands in the first half of 2024:
    sudo (4141 times)
    ls (3562 times)
    cd (2508 times)
```

`sudo` was not listed in the top commands section of `atuin wrapped` or in `atuin stats` which both output:
```
Your Top Commands:
[▮▮▮▮▮▮▮▮▮▮] 3630 ls            
[▮▮▮▮▮▮    ] 2508 cd            
[▮▮▮▮      ] 1495 vim   
```

This occurs when common_prefix is commented out in the config or when it's explicitly stated:
```toml
[stats]
common_prefix = ["sudo"]
```

context for `atuin doctor`:
I have a zfs disk, but the sqlite3 database is on a different disk on an ext4 filesystem (on luks on a GPT partition on an NVMe, nothing too crazy). I have noticed no performance issues so far. 

### Atuin doctor output

```yaml
$ atuin doctor
Atuin Doctor
Checking for diagnostics

[Filesystem] ZFS is known to have some issues with SQLite. Atuin uses SQLite heavily. If you are having poor performance, there are some workarounds here: https://github.com/atuinsh/atuin/issues/952

Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-12-31 7:11:36.031029402 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Fedora Linux",
    "arch": "x86_64",
    "version": "41",
    "disks": [
      {
        "name": "/dev/mapper/luks-1232b6c9-6713-43be-9a26-20c90d0811b5",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "tank",
        "filesystem": "zfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
