### ISSUE TITLE
[Bug]: Terminal prompt is breaking (two-lines)

### ISSUE THREAD

**Issue by DrorDvash** [atuinsh/atuin#2514]
### What did you expect to happen?

terminal prompt should be normal.

### What happened?

I'm using Kali Linux (both 2023.4 and 2024.4), and for unknown reasons, the terminal prompt from time to time breaks up, as you can see in the screenshots:

![image](https://github.com/user-attachments/assets/12e67402-83a9-4665-9443-1c6097048b16)
![image](https://github.com/user-attachments/assets/f690a569-6902-4be0-82eb-fb4bb085639c)
![image](https://github.com/user-attachments/assets/e85adc17-f57f-4a14-9af3-d0cd05bba456)

mostly it happens when I press ctrl+r and leave it open for 15 seconds.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Kali GNU/Linux",
    "arch": "x86_64",
    "version": "2024.4",
    "disks": [
      {
        "name": "/dev/sda1",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
