### ISSUE TITLE
[Bug]:[nushell] not reading config file from ~/.config/atuin/config.toml

### ISSUE THREAD

**Issue by mwmcode** [atuinsh/atuin#2516]
### What did you expect to happen?

Atuin to read config file `~/.config/atuin/config.toml`

<img width="522" alt="image" src="https://github.com/user-attachments/assets/7fe2a598-e74e-4957-862d-9980b368d922" />

```toml
[theme]
name = "marine"

style = "compact"
inline_height = 40

history_filter = [
  "^c$",
  "^cl",
  "^cd",
  "^ls",
  "^rm",
  "^code",
  "^touch",
  "secret",
  "password"
]
```

### What happened?

configs not applied to atuin even after restarting the terminal.

- `style` and `inline_height` are not applied
<img width="1512" alt="Screenshot 2025-01-01 at 1 45 18 pm" src="https://github.com/user-attachments/assets/1162e33c-1ead-4a90-bd0c-a9093f9ac9fc" />

- `history_filter` is not applied
<img width="319" alt="image" src="https://github.com/user-attachments/assets/e904ed84-4c00-4e89-8401-3049e9c6c599" />

### Atuin doctor output

```yaml
❯❯❯ atuin info
Config files:
client config: "~/.config/atuin/config.toml"
server config: "~/.config/atuin/server.toml"
client db path: "/Users/mch/.local/share/atuin/history.db"
key path: "/Users/mch/.local/share/atuin/key"
session path: "/Users/mch/.local/share/atuin/session"

Env Vars:
ATUIN_CONFIG_DIR = "None"

Version info:
version: 18.4.0


❯❯❯ atuin doctor
{
  "atuin": {
    "version": "18.4.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "nu",
    "default": "nu",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.2",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mwmcode** [comment]
`XDG_CONFIG_HOME` was not configured properly.😓

**Comment by mwmcode** [comment]
The only flag that seems to work is [filter_mode](https://docs.atuin.sh/configuration/config/#filter_mode)

**Comment by philtweir** [comment]
I tried to reproduce the missing themes by using just the pasted config.toml, reinstalling atuin 18.4.0 and taking nu 0.101.0 but the marine theme came up fine for me - just to help narrow down, would you be able to confirm it happens with zsh/bash?

Just to be 100% sure, I am guessing it is only how you snippeted your config, but it does look as if the other settings are in the TOML `theme` section and would not be seen - however, for me, the theme name is respected, so even using just that text, I am seeing different behaviour.

**Comment by mwmcode** [comment]
I tried the following 
```toml
[theme]
name = "marine"

style = "compact"
inline_height = 5
```

You're right! The theme is being reflected correctly, but the rest (`style` and `inline_height`) don't seem to work.


- atuin 18.4.0
- zsh 5.9 (arm64-apple-darwin24.0)
