### ISSUE TITLE
[Bug]: ~/.histfile format mismatch

### ISSUE THREAD

**Issue by enometh** [atuinsh/atuin#2517]
### What did you expect to happen?

```
export HISTFILE=~/.histfile  atuin import zsh
```
should import my histfile which has lines of the form
```
: 1589089706:0;cd /usr/share/dbus-1/services
: 1735759004:1;git reset
```

### What happened?

atuin history list shows that the whole line (including the timestamp and duration) are imported,
not jst the commands.
Further There was no way to remove these entries from the database.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0-beta.5",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "emacs",
    "default": "zsh",
    "plugins": [],
    "preexec": null
  },
  "system": {
    "os": "Gentoo",
    "arch": "x86_64",
    "version": "2.14",
    "disks": [
      {
        "name": "rootfs",
        "filesystem": "zfs"
      },
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
