### ISSUE TITLE
[Bug]: Seems to be printing the TUI to the main shell, hiding previous shell output

### ISSUE THREAD

**Issue by FlynnD273** [atuinsh/atuin#2522]
### What did you expect to happen?

Atuin seems to be printing the TUI to the main shell window instead of a separate one. I think this is relatively new behaviour. I've tested it on both Bash and Zsh with the same issue on both. I'm fairly certain it happened after the most recent update, but I'm not entirely sure. I'd expect the shell to look like this after I close the Atuin history window:
```
~ ❱ echo hi there
hi there
~ ❱
```

### What happened?

But the shell output actually looks like this:
```
~ ❱ echo hi there
hi there

~ ❱

<Many blank lines>

  > 3ms    2s ago echo hi there
 [   SESSION    ]
 echo hi there

~ ❱
```

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.4.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Arch Linux",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "systemd-1",
        "filesystem": "autofs"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
