### ISSUE TITLE
[Bug]: Default socket path change in version 18.4.0

### ISSUE THREAD

**Issue by pbek** [atuinsh/atuin#2525]
### What did you expect to happen?

Default socket path should be `~/.local/share/atuin/atuin.sock` according to https://docs.atuin.sh/configuration/config/#socket_path.

### What happened?

Default socket path changed from `~/.local/share/atuin/atuin.sock` (see https://docs.atuin.sh/configuration/config/#socket_path) to `/run/user/<userid>/atuin.sock` from version 18.3.0 to version 18.4.0.

Was this done on purpose?

I got an error message:

```
Error: failed to connect to local atuin daemon at /run/user/1000/atuin.sock. Is it running?

Caused by:
   0: transport error
   1: No such file or directory (os error 2)
   2: No such file or directory (os error 2)

Location:
    /build/source/crates/atuin-daemon/src/client.rs:36:14
```

Manually setting [socket_path](https://docs.atuin.sh/configuration/config/#socket_path) fixed the issue for me.
This is my nix config: https://github.com/pbek/nixcfg/blob/32c4e1456ed7a745f9ef79f828253fa56c6259a3/modules/mixins/common.nix#L269-L327

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-01-05 18:12:09.412342358 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "NixOS",
    "arch": "x86_64",
    "version": "25.05",
    "disks": [
      {
        "name": "/dev/disk/by-uuid/636b91ce-a976-48e5-8e7d-76cfb6b3fce6",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/disk/by-uuid/636b91ce-a976-48e5-8e7d-76cfb6b3fce6",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/sdc3",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
