### ISSUE TITLE
[Bug]: atuin 18.4 ignores `workspaces = true`

### ISSUE THREAD

**Issue by peterjanes** [atuinsh/atuin#2536]
### What did you expect to happen?

1. `~/.config/atuin/config.toml` has `workspaces = true`
2. Current directory contains a `.git` subdirectory
3. Pressing Ctrl+R starts in "WORKSPACE" mode, as in previous versions.

### What happened?

Ctrl+R starts in "GLOBAL" mode. I have to press Ctrl+R three more times to get to "WORKSPACE" mode, toggling through "HOST" and "SESSION". This misbehaviour is consistent across Linux and Mac (I don't have Windows to test) and seems to have been introduced in 18.4.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-01-09 18:04:29.278739 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

```
{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-01-09 18:09:18.009209369 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Fedora Linux",
    "arch": "x86_64",
    "version": "41",
    "disks": [
      {
        "name": "/dev/mapper/VolGroup00-LogVol00",
        "filesystem": "ext3"
      },
      {
        "name": "systemd-1",
        "filesystem": "autofs"
      },
      {
        "name": "/dev/sda1",
        "filesystem": "ext3"
      },
      {
        "name": "/dev/sdb1",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/sdc1",
        "filesystem": "fuseblk"
      }
    ]
  }
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
