### ISSUE TITLE
[Bug]: `atuin-update` Unable to read installation information for app atuin

### ISSUE THREAD

**Issue by quantike** [atuinsh/atuin#2539]
### What did you expect to happen?

When running `atuin-update` I would expect the latest version of atuin to be installed. 

### What happened?

I received the following error with the help message telling me to open an issue.

```sh
➜  ~ atuin-update
Checking for updates...
  × Unable to read installation information for app atuin.
  help: This probably isn't your fault; please open an issue!
```

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-01-09 22:11:15.189998 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.2",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
