### ISSUE TITLE
[Bug]: Ctrl+a not moving cursor to beinning of line

### ISSUE THREAD

**Issue by opransjo** [atuinsh/atuin#2548]
### What did you expect to happen?

Ctrl+a should move cursor to beginning of line, according to https://docs.atuin.sh/configuration/key-binding/#atuin-ui-shortcuts.

### What happened?

The prefix key Ctrl+a conflicts with this, but even changing the prefix key, e.g.

[keys]
prefix = 'q'

does not solve the issue.

The commit "feat: add atuin prefix binding" (https://github.com/atuinsh/atuin/pull/1875), at https://github.com/atuinsh/atuin/commit/b04fc471deb923937b8ef9aab2f39301f8457894, removed `KeyCode::Char('a') if ctrl => self.search.input.start()` from the keybinding handling, which is still not present at https://github.com/atuinsh/atuin/blob/main/crates/atuin/src/command/client/search/interactive.rs#L417 .

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Arch Linux",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
      {
        "name": "/dev/nvme1n1p3",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme1n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/mapper/home",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
