### ISSUE TITLE
[Bug]: altscreen not working on latest release

### ISSUE THREAD

**Issue by r-vdp** [atuinsh/atuin#2551]
### What did you expect to happen?

With the full layout, my terminal used to remain fully visible after exiting atuin, since atuin would draw on the altscreen and not on the main view.
On the latest release however, the terminal viewport always gets cleared.

I usually use alacritty with zellij and fish, but I also tested in foot, without zellij, running bash, and got the same behaviour.

### What happened?

My terminal viewport gets cleared after every atuin history search.

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-01-18 12:35:37.215384305 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "NixOS",
    "arch": "x86_64",
    "version": "25.05",
    "disks": [
      {
        "name": "overlay",
        "filesystem": "overlay"
      },
      {
        "name": "/dev/mapper/volgroup-nixos",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
