### ISSUE TITLE
[Bug]: In some cases, it completely ignores all key press events and only responds for SIGTERM

### ISSUE THREAD

**Issue by Dentrax** [atuinsh/atuin#2559]
### What did you expect to happen?

Nothing, work as-is.

### What happened?

When I press <kbd>CTRL+R</kbd>, Atuin completely ignores any _key press_ events and doesn't respond at all. It only respects for <kbd>CTRL+C</kbd>.

Force quit and reopen the `iTerm2` doesn't resolve the issue. But it works native `Terminal.app`.

The problem started occurring in the last few weeks. (I've no idea what's changed, Autin has been working seamlessly)

I think it just _freezes_. How can I debug further? So that I can able to provide more context for you.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.2",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
