### ISSUE TITLE
[Bug]: atuin 18.4.0 in mprocs 0.7.2 fails with `Error: The cursor position could not be read within a normal duration`

### ISSUE THREAD

**Issue by printfn** [atuinsh/atuin#2560]
### What did you expect to happen?

Running atuin 18.4.0 inside [mprocs](https://github.com/pvolok/mprocs) 0.7.2 should work. It worked on atuin 18.3.0.

I'm not sure if this is due to a bug in atuin or in mprocs.

I wonder if this might be related to the new default layout?

### What happened?

When running atuin 18.4.0 in mprocs 0.7.2, it fails with:

```
Error: The cursor position could not be read within a normal duration

Location:
    crates/atuin/src/command/client/search/interactive.rs:1035:24
```

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-01-22 20:12:53.974980471 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "bash",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "22.04",
    "disks": [
      {
        "name": "none",
        "filesystem": "overlay"
      },
      {
        "name": "drivers",
        "filesystem": "9p"
      },
      {
        "name": "/dev/sdc",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdc",
        "filesystem": "ext4"
      },
      {
        "name": "none",
        "filesystem": "overlay"
      },
      {
        "name": "none",
        "filesystem": "overlay"
      },
      {
        "name": "none",
        "filesystem": "overlay"
      },
      {
        "name": "C:\\134",
        "filesystem": "9p"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
