### ISSUE TITLE
[Bug]: Command search appending instead of executing it.

### ISSUE THREAD

**Issue by dougg0k** [atuinsh/atuin#2561]
### What did you expect to happen?

To run the command or at least replace the current thing written.

### What happened?

Let's say I type `cd` and then `ctrl+r` to search, I find a history, till here it's fine, it's not completely accurate history btw, but that's beside the point.

If I select a command from the list and press enter, the whole command is appended to what is written already.

A `cd /path/` will turn into `cdcd /path/`

---

Edit:

Still, on that first `ctrl+r` mention, it expect you to type from nothing, where it could use what is typed already to automatically give the results.

This makes 2 issues or improvements?!

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "1970-01-01 0:00:00.0 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "nu",
    "default": "nu",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "CachyOS Linux",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
      ...manydisks
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
