### ISSUE TITLE
[Bug]: commands entered with starting spaces / initial spaces / blancs are not added to history

### ISSUE THREAD

**Issue by rpuntaie** [atuinsh/atuin#2566]
### What did you expect to happen?

After transferring a line with indentation from the editor to the command,
I expected to find that line in the history.

### What happened?

I could not find the line with initial spaces / indentation in the history.

### Atuin doctor output

```yaml
atuin doctor                                                                               0(∞)(master|✚4)192.168.1.110/my.git
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.4.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Arch Linux",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
      {
        "name": "/dev/sda3",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sda1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/sdc1",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdd1",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdb1",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
