### ISSUE TITLE
[Bug]: Time in inspector is always shown as UTC

### ISSUE THREAD

**Issue by ninagrosse** [atuinsh/atuin#2567]
### What did you expect to happen?

I'm not sure if this is a bug or intended behavior. When inspecting a command, I expected the command stats to show my local time. But it always shows UTC. My local timezone ist Germany / UTC+1.

If have set `timezone = "local"` in `config.toml` but that doesn't seem to have any effect.

`atuin doctor` output is from WSL2 with Ubuntu. I also tried it on a Debian machine. Same issue.

### What happened?

I did the command at 14:11 local time / UTC+1, but inspector shows 13:11 which is UTC.

![Image](https://github.com/user-attachments/assets/3172a1fc-6ea9-496e-b08c-597689f93afe)

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-01-29 13:11:05.681340372 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "22.04",
    "disks": [
      {
        "name": "/dev/sdd",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdc",
        "filesystem": "ext4"
      },
      {
        "name": "none",
        "filesystem": "9p"
      },
      {
        "name": "none",
        "filesystem": "overlay"
      },
      {
        "name": "/dev/sde",
        "filesystem": "ext4"
      },
      {
        "name": "none",
        "filesystem": "overlay"
      },
      {
        "name": "C:\\134",
        "filesystem": "9p"
      },
      {
        "name": "/dev/sde",
        "filesystem": "ext4"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "/dev/sde",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sde",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sde",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sde",
        "filesystem": "ext4"
      },
      {
        "name": "C:\\134Program\\040Files\\134Docker\\134Docker\\134resources",
        "filesystem": "9p"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
