### ISSUE TITLE
[Bug]: Atuin eats last line from terminal

### ISSUE THREAD

**Issue by rad83** [atuinsh/atuin#2575]
### What did you expect to happen?

I am expecting Atuin not to hiding any output on the terminal.

### What happened?

After selecting command from history (either to run or edit it), when TUI disappears, the terminal shifts one line up thus covering such line. Such behavior happens only if the path is long enough. It may be relevant that I use fish shell and powerline.

The image bellow shows such behavior. The Atuin is invoked by pressing arrow up (between frames 2 and 3), next tab key is pressed to select the command (between frames 3 and 4).

![Image](https://github.com/user-attachments/assets/9376e7ce-c247-4bc6-a0cc-3fb167d40068)

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.4.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "bash",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Arch Linux",
    "arch": "x86_64",
    "version": "unknown",
    "disks": [
      {
        "name": "/dev/nvme0n1p3",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p4",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/loop0",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
