### ISSUE TITLE
[Bug]:   Download from self hosted server silently fails

### ISSUE THREAD

**Issue by mildfuzz** [atuinsh/atuin#2576]
### What did you expect to happen?

When I run this on my server:
```
psql postgres://me:password@0.0.0.0/workbash -c "SELECT COUNT(*) FROM history;"
```

I get this result:
```
 count
-------
 35970
```

So when I run sync, I expect to download a similar number.

### What happened?

```
atuin sync -f
Uploading 11 records to 0194db2645327291819f04bbc71ea1d1/history
12/0 up/down to record store
```
nothung downloads

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-02-07 10:05:51.81126 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.2",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Postgres-2.7.10-17",
        "filesystem": "hfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
