### ISSUE TITLE
[Bug]: Disabling history on the shell, disabled atuin.

### ISSUE THREAD

**Issue by dougg0k** [atuinsh/atuin#2578]
### What did you expect to happen?

To continue working independently.

### What happened?

Today, I set the following config on nushell in attempt to disable history.txt.

```
history: {
	max_size: 0
	isolation: true
}
```

But now, Ctrl + R shows nothing.

```
✗ atuin sync
0/0 up/down to record store
Sync complete! 5693 items in history database, force: false

❯ ? cd
Page 1: records 0 - 0  total: 0
```

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "1970-01-01 0:00:00.0 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "nu",
    "default": "nu",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "CachyOS Linux",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
      ...disks
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
