### ISSUE TITLE
[Bug]: Error: Could not find history file. Try setting and exporting $HISTFILE

### ISSUE THREAD

**Issue by slamp** [atuinsh/atuin#2586]
### What did you expect to happen?

Hello,
It's not really a bug as it's working as expected by I think we can improve it.
Context: I installed atuin on a new PC with a fresh Arch installation. Before the atuin installation, the only thing I did was to follow the zsh new user questionnaire. Then I did atuin login and atuin import zsh

I think atuin should import zsh history when it's the zsh default configuration.

### What happened?

```
❯ ssh mini
Last login: Sat Feb 15 16:58:55 2025 from 192.168.1.121
mini% echo $HISTFILE
/home/slamp/.histfile
mini% atuin import zsh
        Atuin
======================
          🌍
       🐘🐘🐘🐘
          🐢
======================
Importing history...
Importing history from zsh
Error: Could not find history file. Try setting and exporting $HISTFILE`

Location:
    crates/atuin-client/src/import/zsh.rs:38:27


mini% cat .zshrc
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000

setopt autocd extendedglob nomatch notify
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/slamp/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

eval "$(atuin init zsh --disable-up-arrow)"
```

Note: the following command works `export HISTFILE=~/.histfile  atuin import zsh` but the first impression is an error

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-02-15 16:07:54.190783889 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Arch Linux",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
      {
        "name": "/dev/nvme0n1p3",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p3",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
