### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by mzagaja** [atuinsh/atuin#2591]
### What did you expect to happen?

Atuin clears the previous terminal input so I see only atuin text/UI.

### What happened?

I see some of my previous terminal text underneath atuin's UI. 

<img width="1276" alt="Image" src="https://github.com/user-attachments/assets/e18e6ee4-5cf1-4c08-b844-cc3b6e557bc9" />

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.3.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "ted-mediacloud",
        "filesystem": "lucidfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
