### ISSUE TITLE
[Bug]: Broken gray in default color theme in some terminals

### ISSUE THREAD

**Issue by kaueraal** [atuinsh/atuin#2592]
### What did you expect to happen?

Colors are rendered correctly, e.g. in the default color scheme.

### What happened?

In some terminals the default color scheme isn't rendered correctly. The grey is rendered is black. For the default color scheme this affects the color for "Annotation".

Terminal affected are e.g. Kitty, iterm2, and Ghostty.

It's most likely the same issue as in other terminal applications, e.g. [htop](https://github.com/hishamhm/htop/issues/35).

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.3.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
