### ISSUE TITLE
[Bug]: Import for ZSH loads first history file found

### ISSUE THREAD

**Issue by rodrigomideac** [atuinsh/atuin#2593]
### What did you expect to happen?

When running `atuin import zsh` it should import the history that `history` shows and all these commands should be available for atuin.

### What happened?

 `atuin import zsh` imported a legacy history file that I had on `~/.zhistory`, instead of using my `/home/myusername/.zsh_history` that was set on `HISTFILE`.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Manjaro Linux",
    "arch": "x86_64",
    "version": "25.0.0",
    "disks": [
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
