### ISSUE TITLE
[Bug]: When command is prefixed with env vars, the first env var is what counts for `atuin stats`

### ISSUE THREAD

**Issue by douglascamata** [atuinsh/atuin#2594]
### What did you expect to happen?

I run a lot of commands with the AWS profile env var prefixed, like `AWS_PROFILE=dev aws (...)`. 

After some time using Atuin, I expected to see `aws` as my top command.

### What happened?

The top command is just `AWS_PROFILE=dev`, which is not a command per-se.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-02-21 20:35:40.894573 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.3.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
