### ISSUE TITLE
[Bug]: --timezone parameter throws error on negative values

### ISSUE THREAD

**Issue by tessus** [atuinsh/atuin#2608]
### What did you expect to happen?

It should accept the timezone `-5:00`.

### What happened?

```
atuin search --after "2025-03-05" --timezone "-5:00"
error: unexpected argument '-5' found

  tip: to pass '-5' as a value, use '-- -5'

Usage: atuin search [OPTIONS] [QUERY]...

For more information, try '--help'.
```

I don't want to pass `-5` but `-5:00`. Also, if I try `-- -5`, I get another error message.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-03-05 6:00:55.822892 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "blesh"
    ],
    "preexec": "blesh-0.4.0-devel4+4338bbf"
  },
  "system": {
    "os": "Darwin",
    "arch": "x86_64",
    "version": "15.3.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
