### ISSUE TITLE
[Bug]: multiline command does not honor max_preview_height

### ISSUE THREAD

**Issue by tessus** [atuinsh/atuin#2610]
### What did you expect to happen?

I expect atuin to show 4 lines of preview for the multiline command.

### What happened?

Instead only 2 lines are shown:

<img width="1268" alt="Image" src="https://github.com/user-attachments/assets/92e46032-faea-4e10-bd57-b19e0121817d" />

To show that the other command shows 4 lines of preview as configured:

<img width="1266" alt="Image" src="https://github.com/user-attachments/assets/77da2658-598f-421a-8623-0fdee7996264" />

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-03-05 21:04:24.765714 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "blesh"
    ],
    "preexec": "blesh-0.4.0-devel4+4338bbf"
  },
  "system": {
    "os": "Darwin",
    "arch": "x86_64",
    "version": "15.3.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
