### ISSUE TITLE
[Bug]: Alt-n does not work after invoking atuin in Ghostty terminal (Fine with Kitty)

### ISSUE THREAD

**Issue by seungjin** [atuinsh/atuin#2611]
### What did you expect to happen?

Alt-n in Atuin Tui; 
alt + 1 to alt + 9: Select item by the number located near it.

### What happened?

Found that Alt-n in Atuin tui is not working on Ghostty terminal.
It works fine with Kitty though. 
I am using Linux with Fish. 

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-03-06 6:10:48.051354792 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Fedora Linux",
    "arch": "x86_64",
    "version": "41",
    "disks": [
      {
        "name": "/dev/mapper/luks-HIDDEN",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/luks-HIDDEN",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/luks-HIDDEN",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/luks-HIDDEN",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/mapper/luks-HIDDEN",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "sysext",
        "filesystem": "overlay"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
