### ISSUE TITLE
[Bug]: Up binding does not work in fish 4.0

### ISSUE THREAD

**Issue by atanana** [atuinsh/atuin#2613]
### What did you expect to happen?

fish 4.0.0
kitty 0.39.1

up key does not invoke Atuin

### What happened?

up key should invoke Atuin

It seems that problem is in `-k` option. When I manually invoke `bind up _atuin_bind_up` it works fine after that

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-03-07 12:48:49.956389084 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Manjaro Linux",
    "arch": "x86_64",
    "version": "25.0.0",
    "disks": [
      {
        "name": "/dev/sdb4",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdb1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/sdb2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdc1",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sda1",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
