### ISSUE TITLE
[Bug]: Can't register new account

### ISSUE THREAD

**Issue by mhalano** [atuinsh/atuin#2615]
### What did you expect to happen?

I executed `atuin register -u my_user -e my@email.com` and it should work.

### What happened?

I got this message:
```
➜ atuin register -u my_user -e my@email.com
Registering for an Atuin Sync account
Please enter password:
Error: error sending request for url (https://api.atuin.sh/user/mhalano)

Caused by:
   0: client error (Connect)
   1: invalid URL, scheme is not http

Location:
    /build/atuin-GIcDDW/atuin-18.4.0/crates/atuin-client/src/api_client.rs:50:16
```
If I try to access that URL, it says user not found.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": null,
    "sqlite_version": "3.46.1"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "25.04",
    "disks": [
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/nvme1n1p1",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sda1",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
