### ISSUE TITLE
[Bug]: No option to not clear console after opening Atuin

### ISSUE THREAD

**Issue by mhalano** [atuinsh/atuin#2617]
### What did you expect to happen?

I would like to have an option to not clear all the terminal when I open Atunin. I expect that after I close Atuin the prompt is filled with the command but I still she the previous command and its result.

### What happened?

 I usulally need to see the previous command and the result, but they are cleared from screen when I activate Atuin. They don't go away, but I need to scroll up a lot to see them

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-03-09 17:14:45.700135178 +00:00:00"
    },
    "sqlite_version": "3.46.1"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "25.04",
    "disks": [
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/nvme1n1p1",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sda1",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
