### ISSUE TITLE
[Bug]: extra output work with fish shell

### ISSUE THREAD

**Issue by A-caibird** [atuinsh/atuin#2619]
### What did you expect to happen?

1.  use fish shell , and config atuin
2.  select a command, and enter to execute command 
3.  only print output from command 

### What happened?

extra output:
 Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>                                                   (base)
BrokenPipeError: [Errno 32] Broken pipe

![Image](https://github.com/user-attachments/assets/28b77eab-c090-422e-afaa-9cbd27749e45)

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-03-10 3:18:20.377668 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.3.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
