### ISSUE TITLE
[Bug]: When I resize the ghostty terminal window, there is additional panic output.

### ISSUE THREAD

**Issue by A-caibird** [atuinsh/atuin#2632]
### What did you expect to happen?

no

### What happened?

 there is additional output `thread 'main' panicked at std/src/io/stdio.rs:1123:9:`, i use fish and ghostty. 
If I don’t use atuin in fish, this won’t happen.

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-03-17 2:14:28.376707 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.3.2",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
