### ISSUE TITLE
[Bug]: cannot remove key

### ISSUE THREAD

**Issue by donghao1393** [atuinsh/atuin#2655]
### What did you expect to happen?

we should be able to remove a key, like `atuin kv rm some_key`.

### What happened?

it's not support at the moment.
```fish
$ atuin kv rm studio_path
error: unrecognized subcommand 'rm'

Usage: atuin kv <COMMAND>

For more information, try '--help'.
$ atuin kv --help
Get or set small key-value pairs

Usage: atuin kv <COMMAND>

Commands:
  set
  get
  list
  help  Print this message or the help of the given subcommand(s)

Options:
  -h, --help  Print help
```

### Atuin doctor output

```yaml
$ atuin doctor
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.4.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.3.2",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
