### ISSUE TITLE
[Bug]: Last command issued not showing

### ISSUE THREAD

**Issue by cmyk** [atuinsh/atuin#2656]
### What did you expect to happen?

I would expect the last command I issued would show up in history as the last line.

### What happened?

```
│ 7 0s     1h ago source .bashrc                                                                     │
 │ 6 0s     1h ago nvim .bashrc                                                                       │
 │ 5 0s    46m ago nvim .config/nvim/lua/plugins/init.lua                                             │
 │ 4 0s    40m ago nvim .config/nvim/init.lua                                                         │
 │ 3 0s    23m ago nvim ~/.tmux.conf                                                                  │
 │ 2 0s    23m ago nvim ~/.bashrc                                                                     │
 │ 1 0s    22m ago source ~/.bashrc                                                                    │
 │ > 0s    38s ago echo $TMUX
```

The last command was 7 0s. And I can repeatedly write it at my prompt, it NEVER shows up as last in atuin.
This is a blocker for me. Uninstalled until fixed.

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics

[Shell] If you are using Bash, Atuin requires that either bash-preexec or ble.sh be installed. An older ble.sh may not be detected. so ignore this if you have it set up! Read more here: https://docs.atuin.sh/guide/installation/#bash

Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin"
    ],
    "preexec": "unknown"
  },
  "system": {
    "os": "NixOS",
    "arch": "aarch64",
    "version": "24.11",
    "disks": [
      {
        "name": "/dev/disk/by-label/NIXOS_SD",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/disk/by-label/NIXOS_SD",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
