### ISSUE TITLE
[Bug]: '1u' is printed in the beginning of the promp line after exiting atuin menu

### ISSUE THREAD

**Issue by YossiO-BWR** [atuinsh/atuin#2664]
### What did you expect to happen?

Clean prompt shown

### What happened?

I open the menu by Ctrl-R  or UP arrow. I exit the menu by TAB to edit last command or by ESC key.
'1u' text is added to the beginning of the prompt.
Ctrl-C clears it, so does Ctrl-L (without erasing the command that is being edited)

Have this in **Konsole** terminal running in Ubuntu 22.04 and in Kubuntu 22.04 as well.

Happens in Atuin 18.4 but not in 18.3

![Image](https://github.com/user-attachments/assets/7d058ff6-c72c-4ba6-9afb-d35b9ba647c3)

![Image](https://github.com/user-attachments/assets/98e87723-bb3e-4b44-b97b-17f1467bd1ee)

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "22.04",
    "disks": [
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
