### ISSUE TITLE
[Bug]: custom theme does not seem to work

### ISSUE THREAD

**Issue by leonard-slass** [atuinsh/atuin#2671]
### What did you expect to happen?

I have followed the [instructions](https://docs.atuin.sh/guide/theming/#theme-creation):

```
find ~/.config/atuin -type f
/home/tile/.config/atuin/config.toml
/home/tile/.config/atuin/themes/my-theme.toml
```

Relevant excerpt from `config.toml`:

```
[theme]
name = "my-theme"
debug = true
```

```
cat themes/my-theme.toml
[theme]
name = "my-theme"
parent = "autumn"

[colors]
AlertInto = "green"
Guidance = "#888844"
```

I was expecting to get the `autumn` theme with some color modified.

### What happened?

I got the default theme. Setting debug to true did not give me further information.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.4.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Arch Linux",
    "arch": "x86_64",
    "version": "unknown",
    "disks": [
      {
        "name": "/dev/sda2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sda1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/sda6",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/mapper/crypt",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdb1",
        "filesystem": "fuseblk"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
