### ISSUE TITLE
[Bug]: pressing letter "u" followed by the letter "p" on atuin 18.5.0-beta.2 is being treated as up arrow

### ISSUE THREAD

**Issue by msmafra** [atuinsh/atuin#2672]
### What did you expect to happen?

To be able to type "doas dnf upgrade" without having to type the letter "u" + "p" without calling atuin.

### What happened?

Typing "doas dnf upgrade" is being "delayed" when I type the letter "u" because when typing it activates Atuin when using atuin 18.5.0-beta.2 but not on atuin 18.4.0.

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.5.0-beta.2",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-04-06 13:04:05.537665595 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Fedora Linux",
    "arch": "x86_64",
    "version": "41",
    "disks": [
      {
        "name": "/dev/mapper/luks-bca3d61f-75c9-4652-a94c-0ce1249584f3",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/luks-bca3d61f-75c9-4652-a94c-0ce1249584f3",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/luks-bca3d61f-75c9-4652-a94c-0ce1249584f3",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/mapper/luks-318ef4ba-2f0a-4010-b48b-7447fa0723f8",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/luks-318ef4ba-2f0a-4010-b48b-7447fa0723f8",
        "filesystem": "btrfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
