### ISSUE TITLE
[Bug]: duplicate field `enabled` for key `daemon`

### ISSUE THREAD

**Issue by minhtrancccp** [atuinsh/atuin#2682]
### What did you expect to happen?

i'm trying to [enable daemon with home-manager](https://github.com/nix-community/home-manager/blob/master/modules/programs/atuin.nix), which generates the relevant settings in `config.toml` as follows:

```toml
[daemon]
enable = true
```

this should have worked as [`enable`, afaik, is an acceptable alias](./blob/1f6031d84acefd68b2dcc9d3a11eb6203745303f/crates/atuin-client/src/settings.rs#L362)

### What happened?

this error is raised without exceptions:

```log
Error: could not load client settings

Caused by:
    failed to deserialize: duplicate field `enabled` for key `daemon`

Location:
    crates/atuin-client/src/settings.rs:858:26
```

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.5.0-beta.3",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-04-08 1:39:05.48704084 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "bash-preexec"
    ],
    "preexec": null
  },
  "system": {
    "os": "NixOS",
    "arch": "x86_64",
    "version": "25.05",
    "disks": [
      {
        "name": "/dev/disk/by-partlabel/disk-main-root",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/disk/by-partlabel/disk-main-root",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/disk/by-partlabel/disk-main-root",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/disk/by-partlabel/disk-main-root",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/disk/by-partlabel/disk-main-root",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
