### ISSUE TITLE
[Bug]: ui overflows with multi-line tide prompt

### ISSUE THREAD

**Issue by uhthomas** [atuinsh/atuin#2683]
### What did you expect to happen?

The atuin ui should look normal and not overflow the existing prompt.

### What happened?

![Image](https://github.com/user-attachments/assets/ebd24b92-dd7d-47a0-ac4b-11f0e05098ee)

### Atuin doctor output

```yaml
❯ atuin doctor
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-04-08 9:20:48.714038592 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Arch Linux",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
      {
        "name": "/dev/mapper/root",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/mapper/depot",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/fuse",
        "filesystem": "fuse"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
