### ISSUE TITLE
[Bug]: search doesn't respect caps lock

### ISSUE THREAD

**Issue by uhthomas** [atuinsh/atuin#2686]
### What did you expect to happen?

atuin should respect caps lock, so that I can search for things which are in captials.

### What happened?

This is a weird one, and I don't know if it will reproduce for everyone, but atuin just does not respect caps lock for some reason. I will hit the caps lock key, but all the characters in the search bar are lowercase. If caps lock is enabled, and I hold shift, then the characters are still lowercase. If I disable caps lock and hold shift, then the characters do become capitals.

### Atuin doctor output

```yaml
❯ atuin doctor
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.4.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-04-08 22:18:06.634555202 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Arch Linux",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
      {
        "name": "/dev/mapper/root",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/mapper/depot",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
