### ISSUE TITLE
[Bug]: running `atuin status` returns an error on self-hosted instance

### ISSUE THREAD

**Issue by L30Bola** [atuinsh/atuin#2689]
### What did you expect to happen?

TBH I don't quite remember the expected output of the `atuin status` as I've always ran atuin in a self-hosted manner. But for sure it shouldn't be outputting errors.

### What happened?

When I execute `atuin status` I receive this error: 

```
[leonardo.godoy@(⎈|N/A:N/A) 09:28:42 ~]:$ atuin status
Error: unexpected trailing characters; the end of input was expected

Caused by:
    unexpected trailing characters; the end of input was expected

Location:
    crates/atuin-client/src/settings.rs:567:27
[ble: exit 1]
```

Both client and server are on 18.5.0, but I think this has been happening since 18.3.0, maybe even before.
AFAIK, sync is working fine.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.5.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "no last sync"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "blesh",
      "bash-preexec"
    ],
    "preexec": "blesh-0.4.0-devel4+3d8f626"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.3.2",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
