### ISSUE TITLE
[Bug]: [search] filters = [...] not respected over ssh

### ISSUE THREAD

**Issue by merc1031** [atuinsh/atuin#2694]
### What did you expect to happen?

With the following set in `config.toml`
```
[search]
filters = ["workspace", "host", "directory", "session", "global"]
```

It works exactly as expected on a normal terminal, but if i access the machine from a remote terminal via ssh, then it seems to fall back to `global -> host -> directory -> session` instead of respecting  the .toml

### What happened?

Expected to cycle ["workspace", "host", "directory", "session", "global"]

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.5.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-04-11 9:04:45.881968467 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "24.04",
    "disks": [
      {
        "name": "/dev/mapper/ubuntu--vg-ubuntu--lv",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
