### ISSUE TITLE
[Bug]: `[search]` `filters` behaviour inconsistent when used with `workspace` in filter

### ISSUE THREAD

**Issue by merc1031** [atuinsh/atuin#2700]
### What did you expect to happen?

[1]
```
workspaces = true

[search]
filters = ["workspace", "host"]
```
In non git directory, pressing `ctrl+r` expected `host` to come up first 

[2]
```
workspaces = true

[search]
filters = ["workspace", "host", "directory"]
```

In non git directory, pressing `ctrl+r` expected `host` to come up first , then `directory`, then `host`, then `directory` ...

[3]
Works as expected in a git directory

### What happened?

[1] instead `global` comes up, then `host`, then further presses do nothing
[2] instead `global` comes up, then `host`, then `directory` , then `host`, then `directory` ...
[3] pressing `ctrl+r` expected `workspace` to come up first, `host` to come up next , then `directory`, then `worksapce`, then `host` ...

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.5.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-04-14 20:10:41.509478585 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "24.04",
    "disks": [
      {
        "name": "/dev/mapper/ubuntu--vg-ubuntu--lv",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
