### ISSUE TITLE
[Bug]: wrong item selected from history

### ISSUE THREAD

**Issue by sashkab** [atuinsh/atuin#2704]
### What did you expect to happen?

macOS 15.4.1 and atuin 18.5.0

when I press ctrl+r to find history, select item from history wrong item is pasted to the command prompt. 

Can't always reproduce. Usually I do this quickly, ctrl+r, select what I need (by searching, etc) and press enter. 
Few times noticed, wrong command was pasted into prompt from history.  

This happened on at least two occasions just today, which already drove me a bit crazy. When specifically tried, can't reproduce. 

### What happened?

Wrong record was pasted into command prompt from history. let's say I wanted to select line from history where I meant to rerun command to copy file, but instead rm -rf /path which I didn't mean to delete was run. 

### Atuin doctor output

```yaml
$ atuin doctor
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.5.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.4.1",
    "disks": [
      {
        "name": "REDACTED",
        "filesystem": "apfs"
      },
      {
        "name": "REDACTED",
        "filesystem": "apfs"
      },
      {
        "name": "REDACTED",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
