### ISSUE TITLE
[Bug]: Up-key bidning not working with Atuin 18.5.0 / fish 4.0 in some terminal emulators

### ISSUE THREAD

**Issue by pbek** [atuinsh/atuin#2718]
### What did you expect to happen?

When pressing, `Up` the glorious Atuin history should appear in terminal emulator Ghostty or Kitty in Linux.

In Atuin 18.4.0 with the fish 4.0 patch this was working great on NixOS with fish 4.0. After updating to Atuin 18.5.0 it stopped working.
Funny thing is it is still working in Konsole or xterm with Atuin 18.5.0!

### What happened?

Up-Key just adds the previous command to the prompt.
The "up" bindings are still present in fish.

```bash
➜ bind | rg atuin
bind ctrl-r _atuin_search
bind -M insert ctrl-r _atuin_search
bind \eOA _atuin_bind_up
bind \e\[A _atuin_bind_up
bind -M insert -k up _atuin_bind_up
bind -M insert \eOA _atuin_bind_up
bind -M insert \e\[A _atuin_bind_up
```

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.5.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-04-24 9:42:46.782123328 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "NixOS",
    "arch": "x86_64",
    "version": "25.05",
    "disks": [
      {
        "name": "zroot/root",
        "filesystem": "zfs"
      },
      {
        "name": "zroot/root/nix",
        "filesystem": "zfs"
      },
      {
        "name": "zroot/root/nix",
        "filesystem": "zfs"
      },
      {
        "name": "zroot/root/home",
        "filesystem": "zfs"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/sdc3",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
