### ISSUE TITLE
[Bug]: Run script seems to break terminal rendering

### ISSUE THREAD

**Issue by jscarrott** [atuinsh/atuin#2720]
### What did you expect to happen?

I stored a script that ran the helix editor.  I expected that to work normally

### What happened?

It didn't render properly and then didn't accept keys normally. (Some seemed to register but hard to tell due to the rendering issue)

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.5.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-04-25 8:29:01.246569283 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "EndeavourOS",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
