### ISSUE TITLE
[Bug]: scripts: sudo password not getting through

### ISSUE THREAD

**Issue by philn** [atuinsh/atuin#2721]
### What did you expect to happen?

1. Create a script containing ` sudo echo $(whoami)`
2. Run `sudo -k`
3. Run created script

### What happened?

`sudo` prompts for the password but hitting enter key has no visible effect. The prompt remains until the script is interrupted with Ctrl-c.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.5.0",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-04-27 13:48:17.471231688 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Fedora Linux",
    "arch": "x86_64",
    "version": "42",
    "disks": [
      {
        "name": "composefs",
        "filesystem": "overlay"
      },
      {
        "name": "/dev/mapper/fedora-root",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/mapper/fedora-root",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      },
      {
        "name": "/dev/mapper/fedora-home",
        "filesystem": "ext4"
      },
      {
        "name": "sysext",
        "filesystem": "overlay"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
