### ISSUE TITLE
[Bug]: Bash syntax errors not captured

### ISSUE THREAD

**Issue by psalveson** [atuinsh/atuin#2724]
### What did you expect to happen?

If I execute a command that results in a bash syntax error, I expect to see the command that produced the error in atuin (when store_failed = true)

### What happened?

If I execute:
$ echo ($whoami)
-bash: syntax error near unexpected token `$whoami'

There is no sign of "echo ($whoami)" in Atuin.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.5.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Debian GNU/Linux",
    "arch": "x86_64",
    "version": "unknown",
    "disks": [
      {
        "name": "none",
        "filesystem": "overlay"
      },
      {
        "name": "drivers",
        "filesystem": "9p"
      },
      {
        "name": "/dev/sdd",
        "filesystem": "ext4"
      },
      {
        "name": "none",
        "filesystem": "overlay"
      },
      {
        "name": "C:\\134",
        "filesystem": "9p"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
