### ISSUE TITLE
[Bug]: Atuin TUI causes prompt misalignment and corrupted command output on Zsh (macOS, Alacritty/Terminal)

### ISSUE THREAD

**Issue by jordanpmc** [atuinsh/atuin#2728]
### What did you expect to happen?

After triggering Atuin via the up-arrow key in Zsh, I expected the terminal to:

- Restore the prompt correctly (with proper spacing and cursor alignment)

- Display any injected command output with correct line breaks and formatting

- Leave the terminal in a usable, sane state without requiring reset or restart

### What happened?

When Atuin's interactive TUI is triggered via the up-arrow key and then exited (by selecting a command or pressing escape):

- The shell prompt becomes misaligned, with the $ symbol indented or offset.
- The output of the restored command is broken, with incorrect line breaks or spacing.
- This corruption persists until the terminal is reset or restarted.

The issue occurs even in a clean Zsh environment (zsh -f) with no plugins or theme, and is reproducible in both Alacritty and macOS Terminal.

The root cause seems to be Atuin leaving the terminal in an inconsistent TTY state after exiting its TUI interface—likely failing to reset stty flags or restore from raw mode.

<img width="624" alt="Image" src="https://github.com/user-attachments/assets/0630123f-edcf-4ba7-a10a-d1575ace6858" />

<img width="455" alt="Image" src="https://github.com/user-attachments/assets/817ab9b5-6e86-45e2-a0ea-1cca101fe494" />

**Temporary Workaround**
Adding the following functions to .zshrc (after eval "$(atuin init zsh)") resolves the issue by manually resetting the terminal before and after each command:

```
eval "$(atuin init zsh)"

_atuin_fix_echo() {
    stty echo
    stty sane
}

precmd_functions+=(_atuin_fix_echo)
preexec_functions+=(_atuin_fix_echo)
```

This restores prompt and output correctness, but is not ideal.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.5.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.4.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
