### ISSUE TITLE
Ctrl-h/j/k/l pane navigation in tmux conflicts with Atuin

### ISSUE THREAD

**Issue by szcharlesji** [atuinsh/atuin#2733]
### What did you expect to happen?

I used to use fzf to navigate which did not have this problem. When the active pane is running the Atuin, hitting `Ctrl-h/j/k/l` should move the cursor *inside* atuin, not switch tmux panes.

### What happened?

I’m using [vim-tmux-navigator](https://github.com/christoomey/vim-tmux-navigator) to move between tmux panes with `Ctrl-h/j/k/l`.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.5.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-05-05 0:05:58.312001 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.4.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
