### ISSUE TITLE
[Bug]: tab select occasionally choses last unset command when env var is used in selected command

### ISSUE THREAD

**Issue by mtougeron** [atuinsh/atuin#2737]
### What did you expect to happen?

Using zsh on macos 15.4 in terminal, I have the following command (an similar) in my history

```
VAULT_TOKEN=$(cat ~/.vault-token) make cluster
```

when I type in the first few characters `VAU` and then hit the up arrow to scroll up to select the command I want to use and then hit the tab key to select the line so I can make modifications, it will occasionally select the most recent `unset` command in the history that was executed instead of the command (as shown above) that was highlighted.

This only appears to happen when the `unset` command happens _after_ the commend with the env variable in it. For example, if I run the above command, then several other commands, then go back and try to select that command again it seems to work fine. However, if I run an `unset` in-between it will choose the unset instead.

Also worth noting, in case this makes a difference, is that I'm using [oh-my-zsh](https://ohmyz.sh/) with these plugins `git github gitfast git-extras kubectl history macos python`

### What happened?

Instead of filling `VAULT_TOKEN=$(cat ~/.vault-token) make cluster` it filled `unset KUBECONFIG` when I hit the tab key.

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.5.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-05-05 17:07:43.301768 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.4",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
