### ISSUE TITLE
[Bug]: bash prompt customization (starship.rs) broken after atuin integration

### ISSUE THREAD

**Issue by sebastianschauenburg** [atuinsh/atuin#2738]
### What did you expect to happen?

Expected the (previously working) starship bash prompt customization, to keep working.

OS: Ubuntu 24.10 (bash 5.2.32)
Starship versions  tested: 1.22.1 and 1.23.0
Also tested with atuin disabled, and manually loaded atuin. As soon as that happens, the prompt appears to be broken.
Only tested it on 1 machine, so it might be a 'just me' error.

Example prompt:
```user@host:ansible  develvia 🐍 v3.12.7 $ ```

### What happened?

The prompt actually shown, is my default prompt (so without the starship customization/change):
```user@host:~/git_clone/ansible$```

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.5.0",
    "sync": {
      "cloud": false,
      "records": false,
      "auto_sync": true,
      "last_sync": "2025-05-05 7:17:52.845683025 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "atuin",
    "default": "bash",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "24.10",
    "disks": [
disks omitted
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
