### ISSUE TITLE
[Bug]: UI shows one command selected, pressing tab sends a different command back to the shell

### ISSUE THREAD

**Issue by douglascamata** [atuinsh/atuin#2739]
### What did you expect to happen?

I expected the command I selected to appear in the shell.

### What happened?

As you can see in the video, I select a `docker run [...]` command, then I press `<tab>` to edit it before running. To my surprise a different command is returned to edit!

Interestingly enough, pressing `<enter>` to directly execute the command behaves as expected, correctly executing the entry I selected.

https://github.com/user-attachments/assets/1a0d2e5f-2061-43a8-9b21-981f2f13091a

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.5.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-05-06 9:24:11.274218 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.4.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
