### ISSUE TITLE
[Bug]: error `__bp_last_argument_prev_command: parameter null or not set`

### ISSUE THREAD

**Issue by Yury-Fridlyand** [atuinsh/atuin#2741]
### What did you expect to happen?

Snippet from `~/.bashrc`:
```
. "$HOME/.atuin/bin/env"

[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh
# https://docs.atuin.sh/configuration/key-binding/#bash
export ATUIN_NOBIND="true"
eval "$(atuin init bash)"
# bind to ctrl-r
bind -x '"\C-r": __atuin_history'
```

I expect to pop a command from history and run.

### What happened?

Sometimes I'm getting error
```
bash: __bp_last_argument_prev_command: parameter null or not set
```
after getting a command from history from Atuin (`Ctrl+R`) or using arrow keys.

This started to appear recently

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.3.0",
    "sync": null,
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "24.04",
    "disks": [
      {
        "name": "none",
        "filesystem": "overlay"
      },
      {
        "name": "/dev/sdc",
        "filesystem": "ext4"
      },
      {
        "name": "drivers",
        "filesystem": "9p"
      },
      {
        "name": "/dev/sde",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sde",
        "filesystem": "ext4"
      },
      {
        "name": "none",
        "filesystem": "overlay"
      },
      {
        "name": "none",
        "filesystem": "overlay"
      },
      {
        "name": "none",
        "filesystem": "overlay"
      },
      {
        "name": "C:\\134",
        "filesystem": "9p"
      },
      {
        "name": "/dev/sde",
        "filesystem": "ext4"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "snapfuse",
        "filesystem": "fuse.snapfuse"
      },
      {
        "name": "/dev/sde",
        "filesystem": "ext4"
      }
    ]
  }
}

(WSL)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
