### ISSUE TITLE
[Bug]: Panick "Drawing inspector, but no stats"

### ISSUE THREAD

**Issue by ziadkh0** [atuinsh/atuin#2744]
### What did you expect to happen?

The inspector opens after pressing <ctrl-o> to open the inspector.

### What happened?

atuin crashed after pressing <ctrl-o> to open the inspector with the following message:

```
thread 'main' panicked at crates/atuin/src/command/client/search/interactive.rs:791:32:
Drawing inspector, but no stats
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.6.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.4.1",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "macOS Sequoia",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
