### ISSUE TITLE
[Bug]: panic when trying to inspect command

### ISSUE THREAD

**Issue by sashkab** [atuinsh/atuin#2755]
### What did you expect to happen?

I run `brew upgrade` frequently. Wanted to see atuin's inspect sheet for statistics, because ctrl+r showed me I ran it 40 seconds ago. Wanted to see if I can get when I ran it previous time.

### What happened?

Atuin crashed the moment I pressed Ctrl+O. Set `export RUST_BACKTRACE=full` and here is the trace:

```
thread 'main' panicked at crates/atuin/src/command/client/search/interactive.rs:791:32:
Drawing inspector, but no stats
stack backtrace:
   0:        0x103db9cf0 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::he95167bc0db69172
   1:        0x103dd6d48 - core::fmt::write::h7a9b1a2c5a4d720d
   2:        0x103d9ec98 - std::io::Write::write_fmt::h6ba1180d709be9ef
   3:        0x103db9ba4 - std::sys::backtrace::BacktraceLock::print::he986caf53af0c7c0
   4:        0x103dbf44c - std::panicking::default_hook::{{closure}}::h91abe66414d5ff97
   5:        0x103dbf360 - std::panicking::default_hook::hd88a7d3ab5420733
   6:        0x103dbf9dc - std::panicking::rust_panic_with_hook::h0c4570804070c568
   7:        0x103dba110 - std::panicking::begin_panic_handler::{{closure}}::h137406384c01ca5e
   8:        0x103db9f54 - std::sys::backtrace::__rust_end_short_backtrace::hbbf6c8bb05b960c8
   9:        0x103dbf4e8 - _rust_begin_unwind
  10:        0x103e33320 - core::panicking::panic_fmt::h8df0ae8acbd1e44d
  11:        0x103e33008 - core::option::expect_failed::h8b523aba43694a7e
  12:        0x10307d0b4 - atuin::command::client::search::interactive::State::draw::hb68e578588f3ed40
  13:        0x103074568 - ratatui::terminal::terminal::Terminal<B>::draw::h7f2288f972e12f58
  14:        0x102ee62bc - atuin::command::client::search::Cmd::run::{{closure}}::h4f19ad3bf62e0d9e
  15:        0x102ef04cc - atuin::command::client::Cmd::run_inner::{{closure}}::hd18cd9dd9aa71099
  16:        0x103234194 - tokio::runtime::context::scoped::Scoped<T>::set::h66c38ba877e4be61
  17:        0x103236004 - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::he17cb3f14b1bb248
  18:        0x10317463c - tokio::runtime::context::runtime::enter_runtime::h5e4c2ea8eac33c6d
  19:        0x1032b07d0 - tokio::runtime::runtime::Runtime::block_on::hb21821f3a73afd62
  20:        0x103182fa0 - atuin::main::h280230835a1f52cd
  21:        0x10320f97c - std::sys::backtrace::__rust_begin_short_backtrace::h9dfbd18dca925bed
  22:        0x1031226c4 - std::rt::lang_start::{{closure}}::h51bbdf78ffc73c4d
  23:        0x103d9bb28 - std::rt::lang_start_internal::h617365ae9557c7bb
  24:        0x1031ac368 - _main
```

### Atuin doctor output

```yaml
$ atuin doctor
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.6.0",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.4.1",
    "disks": [
      {
        "name": "xxx",
        "filesystem": "apfs"
      },
      {
        "name": "xxx",
        "filesystem": "apfs"
      },
      {
        "name": "xxx",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
