### ISSUE TITLE
[Bug]: Major regression in performance when searching history

### ISSUE THREAD

**Issue by yretenai** [atuinsh/atuin#2763]
### What did you expect to happen?

Atuin to not freeze and to not use 100% CPU.

### What happened?

When you type the start of any command and press up, it freezes the entire console depending on the search complexity of the query.

"cd" for example is near instantaneous, but "cd start/of/some/path" pins atuin at 100% CPU usage for several hours. You can see this gradual slow down the more letters are input to the search.

I have a 5.4 GHz processor, this slowdown behavior was not present-- at least not noticeable in 18.5.0.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.6.1",
    "sync": null,
    "sqlite_version": "3.49.1"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Gentoo",
    "arch": "x86_64",
    "version": "2.17",
    "disks": [
      {
        "name": "/dev/nvme1n1p3",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme1n1p2",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme1n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
