### ISSUE TITLE
Support to move left and backspace in history

### ISSUE THREAD

**Issue by fepegar** [atuinsh/atuin#2773]
Hi, and thanks for sharing this amazing tool.

Something I did a lot before using atuin was fixing the last part of the last command, or something in the middle. For that, I'd press Up and then backspace (for the former) or Left (for the latter). I think to do that with atuin, I need to press TAB after Up. Is it possible to not have to press TAB in this situation?

**Comment by pveierland** [comment]
Yes, I just started using atuin and second this. A common UX coming from bash was to press `up` then `home` or `end` as well, to then directly edit the command from the start or end.

**Comment by chinigo** [comment]
And my personal habit is (was) to use `ctrl-a`, `ctrl-b`, etc, to position myself within the previous command before editing. Others will have other tics, of course.

Perhaps the feature request is for any keystroke *other than* enter, tab, or other reserved atuin bindings to 1) accept atuin's suggestion and then 2) send that keystroke to the shell?

**Comment by ellie** [comment]
This is all doable with config now!

Since 18.10 there are a couple of keys options that cover exactly this:

```toml
[keys]
accept_with_backspace = true   # backspace on an empty search hands the command back to your shell for editing
accept_past_line_start = true  # same for pressing left at the start of the line
```

Right arrow at the end of the line already does this by default (`accept_past_line_end`).

For anything beyond that (home/end, ctrl+a, whatever your muscle memory wants), 18.12 added a full keymap system where any key can be bound to `return-selection` - including conditionally, e.g.

```toml
[keymap.emacs]
"left" = [
  { when = "cursor-at-start", action = "return-selection" },
  { action = "cursor-left" },
]
```

Docs here: https://docs.atuin.sh/configuration/key-binding/
