### ISSUE TITLE
[Bug]: Searching with all-caps search term gives wrong result on hitting return

### ISSUE THREAD

**Issue by mrnugget** [atuinsh/atuin#2782]
### What did you expect to happen?

* I search for `UNSAFE` because I want to run `UNSAFE_DEV_AUTH_BYPASS=1 pnpm dev`
* `UNSAFE_DEV_AUTH_BYPASS=1 pnpm dev` shows up in results
* I hit return
* I get a different command

### What happened?

* I get `pnpm check` even though it wasn't even in the list

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.6.1",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-06-05 11:54:21.900634 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.5",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
