### ISSUE TITLE
[Bug]: Long Loading Time on Trigger and then Panic in client.rs

### ISSUE THREAD

**Issue by svenliebig** [atuinsh/atuin#2783]
### What did you expect to happen?

Opening the recent used commands when I press keyup.

### What happened?

The programm panicked and send this error message:

thread 'main' panicked at /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-1949cf8c6b5b557f/reqwest-0.11.27/src/async_impl/client.rs:1713:38:
Client::new(): reqwest::Error { kind: Builder, source: Custom { kind: Other, error: Error { code: -36, message: "I/O error." } } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: task 5 panicked with message "Client::new(): reqwest::Error { kind: Builder, source: Custom { kind: Other, error: Error { code: -36, message: \"I/O error.\" } } }"

Location:
    crates/atuin/src/command/client/search/interactive.rs:1183:374;20M

![Image](https://github.com/user-attachments/assets/f7b20bfd-d21e-496f-80e6-81acd033c3c1)

What I tried:
- uninstalled via brew
- reinstalled via brew

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.6.1",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "15.5",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
