### ISSUE TITLE
[Bug]: Online config file documentation is inconsistent with example config file

### ISSUE THREAD

**Issue by blackbit42** [atuinsh/atuin#2786]
### What did you expect to happen?

The online documentation at [d.a.s/configuration/config/](https://docs.atuin.sh/configuration/config/) should list all configuration options that are present in [config.toml](https://github.com/atuinsh/atuin/blob/main/crates/atuin-client/config.toml) and only those.

### What happened?

The following options are documented in [config.toml](https://github.com/atuinsh/atuin/blob/main/crates/atuin-client/config.toml) but not at [d.a.s/configuration/config/](https://docs.atuin.sh/configuration/config/):
```
timezone
word_jump_mode
word_chars
scroll_context_lines
auto_hide_height

[stats]
ignored_commands

[keys]
exit_past_line_start
accept_past_line_end

[search]
filters
```

The following options are documented at [d.a.s/configuration/config/](https://docs.atuin.sh/configuration/config/) but not in [config.toml](https://github.com/atuinsh/atuin/blob/main/crates/atuin-client/config.toml):
```
store_failed

[keys]
prefix

[dotfiles]
enabled

[theme]
max_depth
```

It is not entirely clear to me which of the two should be considered the source of truth.
Please make the documentation consistent or advise what should be considered correct. I am happy to draft a PR.

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.6.1",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Debian GNU/Linux",
    "arch": "x86_64",
    "version": "12",
    "disks": [
      {
        "name": "/dev/mapper/memex--vg-root",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext2"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
