### ISSUE TITLE
[Bug]: Extra characters when submitting tab-selected command (Ghostty terminal)

### ISSUE THREAD

**Issue by ttrei** [atuinsh/atuin#2789]
### What did you expect to happen?

1. Select a command from history for editing.
2. Execute the command.

Only output of the command printed to screen.

### What happened?

Extra random characters printed before the expected output.

**Environment**
[ghostty](https://ghostty.org/) 1.1.3
atuin 18.6.1
bash 5.2.37
NixOS 25.05

**How to reproduce**
Created a vm specification for easier reproduction: https://github.com/ttrei/atuin/blob/repro/repro/flake.nix
```
git clone https://github.com/ttrei/atuin.git
cd atuin
git checkout repro
cd repro
nix build .#nixosConfigurations.repro-vm.config.system.build.vm && result/bin/run-nixos-vm
```
Login admin/a
Applications -> Run Program -> ghostty
```
ls
<up><tab><enter>
```
May have to try it a few times before the extra characters appear.

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.6.1",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-06-11 20:58:50.770188098 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "NixOS",
    "arch": "x86_64",
    "version": "25.05",
    "disks": [
      {
        "name": "/dev/disk/by-uuid/77e6b686-47f7-4a6c-ae1b-a2131c4adcbd",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/disk/by-uuid/77e6b686-47f7-4a6c-ae1b-a2131c4adcbd",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sdb1",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
