### ISSUE TITLE
[Bug]: atuin sync is slow for large history

### ISSUE THREAD

**Issue by indigoviolet** [atuinsh/atuin#2793]
### What did you expect to happen?

My history has 60K items, and I regularly want to spin up new machines and initialize history there. atuin sync is very slow at this point. How can I speed it up?

- I have run atuin history dedup --dupkeep 1 --before '1 day' but I'm not sure I understand what this does or how the parameters work

- I would like atuin sync --from '3 days ago' or something like this

### What happened?

`atuin sync` is slow with multiple progressbars downloading history items

### Atuin doctor output

```yaml
tuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.6.1",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-06-13 18:39:35.439611903 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Debian GNU/Linux",
    "arch": "x86_64",
    "version": "12",
    "disks": [
      {
        "name": "overlay",
        "filesystem": "overlay"
      },
      {
        "name": "/dev/nvme0n2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
