### ISSUE TITLE
[Bug]: Commands coming from $EDITOR (vi-mode) are not saved

### ISSUE THREAD

**Issue by amorenoz** [atuinsh/atuin#2795]
### What did you expect to happen?

I use bash and readline in vi-mode (`set -o vi`). In  this mode, when you press "v" (alas visual mode in vi), it opens your `$EDITOR` with the content of the line. When you later save and close your editor, readline will pick up its content and send it to your terminal.

I was naively expecting atuin to save the commands added this way.

### What happened?

When I use this mode to type commands, atuin is not saving them.

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.6.1",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": null
  },
  "system": {
    "os": "Fedora Linux",
    "arch": "x86_64",
    "version": "42",
    "disks": [
      {
        "name": "/dev/mapper/luks-ff641373-befb-446b-a6b8-eae11dacc4b1",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/luks-ff641373-befb-446b-a6b8-eae11dacc4b1",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
