### ISSUE TITLE
[Bug]:  slow down the shell

### ISSUE THREAD

**Issue by skarpinis** [atuinsh/atuin#2796]
### What did you expect to happen?

The shell should not be slowed down.

### What happened?

I have 100 lines of eval "$(atuin init zsh)" in my ~/.zshrc file. Every time I open a new shell, a new line appears. 

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.6.1",
    "sync": {
      "cloud": false,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-06-17 8:57:55.371032505 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "zsh",
    "default": "zsh",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Arch Linux",
    "arch": "x86_64",
    "version": "unknown",
    "disks": [
      {
        "name": "/dev/mapper/luks-",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/luks-",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/luks-",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/luks-",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/luks-",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
