### ISSUE TITLE
[Bug]: atuin scripts edit does not give the intended error message if editor is not found

### ISSUE THREAD

**Issue by mikran** [atuinsh/atuin#2798]
### What did you expect to happen?

Most "atuin scripts" are failing, after inspecting code from the errored line, I was expecting this error

["failed to open editor"](https://github.com/atuinsh/atuin/blob/main/crates/atuin/src/command/client/scripts.rs#L137)

### What happened?

```
❯ atuin scripts new test                                                                                                                                                                                                                                                            07:06:30
Error: No such file or directory (os error 2)

Location:
    crates/atuin/src/command/client/scripts.rs:135:22
```

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.6.1",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-06-19 4:12:51.705337706 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Arch Linux",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
      {
        "name": "/dev/mapper/root",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/root",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/root",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/mapper/root",
        "filesystem": "btrfs"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
