### ISSUE TITLE
[Bug]: Atuin remote address incorrectly displays default after local configuration

### ISSUE THREAD

**Issue by krenax** [atuinsh/atuin#2802]
### What did you expect to happen?

When configuring Atuin to sync with a local self-hosted server, the atuin status command incorrectly displays https://api.atuin.sh as the remote address, even though the configuration points to a local IP address. This gives a misleading impression that the client is still syncing with the default public Atuin server, while it is actually attempting to connect to the configured local server.

### What happened?

atuin status
Atuin v18.6.1 - Build rev 84589cab15253300984bfaca1392795c39d137fc

[Local]
Sync frequency: 5m
Last sync: 2025-06-24 14:57:00.361835678 +02:00:00
[Remote]
Address: https://api.atuin.sh
Username: kre

### Atuin doctor output

```yaml
{
  "atuin": {
    "version": "18.6.1",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2025-06-24 13:02:19.555611774 +00:00:00"
    },
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "24.04",
    "disks": [
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sda1",
        "filesystem": "ext4"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
