### ISSUE TITLE
[Bug]: Commands not saved to history seemingly randomly

### ISSUE THREAD

**Issue by bbutler3** [atuinsh/atuin#2804]
### What did you expect to happen?

I expect every command I run in the command line to appear in the `atuin` history, accessible via up-arrow or ctrl+R (or `atuin history list`). 

### What happened?

I am on Ubuntu 24.04.2 LTS.

Sometimes commands save without issue. But sometimes commands are not saved after they're run. I cannot determine a pattern to this. For example, in my current session, sometimes `ls` and `ls -lhrt` are saved, and sometimes they aren't. This can change within a couple of minutes, with nothing of note run in between (maybe a `cd` or something else trivial). `sudo apt update` and `sudo apt upgrade` have not been recorded at all either time I've run them. `emacs` commands also sometimes don't appear. All of these have appeared in the past as normal before. `atuin doctor` also does not appear.

I noticed this issue last week and was unable to solve it through any means I could think of (including terminal/shell restarts, logging out, and restarting entirely). Nothing reliably worked. It would seem fine for a few minutes, and then break again. I eventually decided to save my `history.db` elsewhere and completely uninstall and reinstall `atuin` (replacing my history afterward). Things seemed to be fixed after that, and I went on about my business. But now it's broken again in the same way. 

I really can't find any pattern or reason to this, so I'm hoping you can help. Thanks!

### Atuin doctor output

```yaml
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.6.1",
    "sync": null,
    "sqlite_version": "3.46.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Ubuntu",
    "arch": "x86_64",
    "version": "24.04",
    "disks": [
      {
        "name": "/dev/nvme0n1p2",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/nvme0n1p1",
        "filesystem": "vfat"
      }
    ]
  }
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
